/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/test/stage-test.glb 
*/

import React, { useEffect, useRef } from "react";
import { useFrame, useLoader } from "@react-three/fiber";
import { useGLTF, useVideoTexture, Mask, useMask } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";

export default function StageTest(props) {
  /**
   * TEXTURE FOR MESH TRANSMISSION MATERIAL
   */
  const abstractOrganic02NormalTexture = useLoader(
    THREE.TextureLoader,
    "./textures/abstract-organic/Abstract_Organic_002_NORM.jpg"
  );

  const GLASS_MATERIAL_02 = new THREE.MeshPhysicalMaterial({
    color: "#ffffff",
    roughness: 0.15,
    transmission: 1,
    thickness: 0.5,
    normalMap: abstractOrganic02NormalTexture,
  });

  /**
   * MASK STENCIL
   */
  const stencil = useMask(1);

  /**
   * VIDEOS FOR THE BEAUTY OF TIME PASSING PROJECT
   */
  const springVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/spring.mp4"
  );
  const summerVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/summer.mp4"
  );
  const autumnVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/autumn.mp4"
  );
  const winterVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/winter.mp4"
  );

  /**
   * VIDEO FOR DIGITAL SCENERY
   */
  const binaryNumbersBackgroundVideo = useVideoTexture(
    "./videos/beauty-of-time-passing/binary-numbers-resize-40perc.mp4"
  );
  binaryNumbersBackgroundVideo.wrapS = THREE.RepeatWrapping;
  binaryNumbersBackgroundVideo.wrapT = THREE.RepeatWrapping;
  binaryNumbersBackgroundVideo.flipY = false;
  binaryNumbersBackgroundVideo.repeat.set(3, 3);

  /**
   * VIDEOS FOR THE 3D VIDUALS
   */
  const silkySphereVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Silkey_Sphere.mp4"
  );

  silkySphereVideoTexture.wrapS = THREE.RepeatWrapping;
  silkySphereVideoTexture.wrapT = THREE.RepeatWrapping;
  silkySphereVideoTexture.flipY = false;

  const bloomingFlowerVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Blooming_Flower.mp4"
  );

  bloomingFlowerVideoTexture.wrapS = THREE.RepeatWrapping;
  bloomingFlowerVideoTexture.wrapT = THREE.RepeatWrapping;
  bloomingFlowerVideoTexture.flipY = false;

  const dancingTentacleVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Dancing_Tentacles.mp4"
  );

  dancingTentacleVideoTexture.wrapS = THREE.RepeatWrapping;
  dancingTentacleVideoTexture.wrapT = THREE.RepeatWrapping;
  dancingTentacleVideoTexture.flipY = false;

  const glassPoppingVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Glass_Popping.mp4"
  );

  glassPoppingVideoTexture.wrapS = THREE.RepeatWrapping;
  glassPoppingVideoTexture.wrapT = THREE.RepeatWrapping;
  glassPoppingVideoTexture.flipY = false;

  const beautyOfTimePassingVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Beauty_Of_Time_Passing.mp4"
  );

  beautyOfTimePassingVideoTexture.wrapS = THREE.RepeatWrapping;
  beautyOfTimePassingVideoTexture.wrapT = THREE.RepeatWrapping;
  beautyOfTimePassingVideoTexture.flipY = false;

  const sakuraPetalsVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Sakura_Petals.mp4"
  );

  sakuraPetalsVideoTexture.wrapS = THREE.RepeatWrapping;
  sakuraPetalsVideoTexture.wrapT = THREE.RepeatWrapping;
  sakuraPetalsVideoTexture.flipY = false;

  const squishyObjectsVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Squishy_Objects.mp4"
  );

  squishyObjectsVideoTexture.wrapS = THREE.RepeatWrapping;
  squishyObjectsVideoTexture.wrapT = THREE.RepeatWrapping;
  squishyObjectsVideoTexture.flipY = false;

  const sequenceRiverVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Sequence_River.mp4"
  );

  sequenceRiverVideoTexture.wrapS = THREE.RepeatWrapping;
  sequenceRiverVideoTexture.wrapT = THREE.RepeatWrapping;
  sequenceRiverVideoTexture.flipY = false;

  /**
   * MODEL -------------------------------------------------------
   */

  const { nodes, materials } = useGLTF("./models/test/stage-test.glb");

  const comfortingDinnerTextTouch = useRef();
  const comfortingDinnerTextSmell = useRef();
  const comfortingDinnerTextListen = useRef();
  const comfortingDinnerTextLook = useRef();
  const comfortingDinnerTextTaste = useRef();

  useEffect(() => {
    if (comfortingDinnerTextTouch) {
      comfortingDinnerTextTouch.current.material.transparent = true;
      comfortingDinnerTextTouch.current.material.opacity = 0.25;
    }
  }, []);

  useFrame((state, delta) => {
    comfortingDinnerTextTouch.current.rotation.y += delta * 0.3;
    comfortingDinnerTextSmell.current.rotation.y += delta * 0.3;
    comfortingDinnerTextListen.current.rotation.y += delta * 0.3;
    comfortingDinnerTextLook.current.rotation.y += delta * 0.3;
    comfortingDinnerTextTaste.current.rotation.y += delta * 0.3;
  });

  return (
    <group {...props} dispose={null}>
      <mesh scale={[52, 38, 1]} position={[
        15, 22, -45]} material={GLASS_MATERIAL_02}>
        <planeGeometry />
      </mesh>

      <mesh
        geometry={nodes.glassBrick01006.geometry}
        material={materials["glass-low-poly.002"]}
        position={[-141.341, 40.989, -91.752]}
        rotation={[-2.736, -0.377, 1.228]}
        scale={8.516}
      />
      <mesh
        geometry={nodes.glassBrick02006.geometry}
        material={materials["glass-low-poly.002"]}
        position={[-151.711, 25.473, -111.1]}
        rotation={[-3.008, -0.345, 2.012]}
        scale={8.516}
      />
      <mesh
        geometry={nodes["led-light-socket003"].geometry}
        material={materials["black-low-poly"]}
        position={[-153.408, 55.221, -87.109]}
        rotation={[0.782, -0.469, 0.297]}
        scale={[50.274, 2.279, 50.274]}
      />
      <mesh
        geometry={nodes["led-light-wire-curve010"].geometry}
        material={materials["black-low-poly"]}
        position={[-163.994, 53.056, -82.21]}
        rotation={[1.971, 0.634, 2.709]}
        scale={10.133}
      />
      <mesh
        geometry={nodes["wood-frame-bottom003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-137.494, 14.316, -109.203]}
        rotation={[1.308, -0.821, 1.052]}
        scale={[5.32, 0.76, 6.1]}
      />
      <mesh
        geometry={nodes["wood-frame-left003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-132.913, 46.674, -112.322]}
        rotation={[-2.332, 0.788, 2.424]}
        scale={[5.32, 16.973, 0.76]}
      />
      <mesh
        geometry={nodes["wood-frame-right003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-166.628, 20.551, -91.242]}
        rotation={[1.107, -0.429, 0.975]}
        scale={[5.32, 16.973, 0.76]}
      />
      <mesh
        geometry={nodes["wood-frame-top003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-164.181, 52.669, -78.997]}
        rotation={[-1.655, 0.54, -0.675]}
        scale={[5.32, 0.76, 6.1]}
      />
      <mesh
        geometry={nodes["wood-stick-back003"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[-141.957, 19.306, -100.228]}
        rotation={[2.078, 0.793, 1.203]}
        scale={[10.133, 6.84, 10.133]}
      />
      <mesh
        geometry={nodes["wood-stick-front003"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[-160.273, 35.23, -102.254]}
        rotation={[0.981, 0.367, 0.89]}
        scale={[10.133, 6.84, 10.133]}
      />
      <mesh
        geometry={nodes["glass-brick-window-modified"].geometry}
        material={materials["glass-low-poly"]}
        position={[-196.325, 58.87, -111.229]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.557}
      />

      {/* MASK - SCENERY CIRCLE WINDOW */}
      <Mask
        id={1}
        geometry={nodes["scenery-window-mask"].geometry}
        position={[-133.89, 27.759, -244.059]}
        rotation={[Math.PI / 2, 0, -1.135]}
        scale={7.427}
      >
        <meshBasicMaterial />
      </Mask>

      <group
        position={[-133.07, 28.155, -243.952]}
        rotation={[0, 1.135, 0]}
        scale={34.481}
      >
        <mesh
          geometry={nodes.Plane110.geometry}
          material={materials["black-low-poly"]}
        />
        <mesh
          geometry={nodes.Plane110_1.geometry}
          material={materials["paper-screen-white"]}
        />
      </group>

      <mesh
        geometry={nodes["circle-window-frame"].geometry}
        material={materials["black-low-poly"]}
        position={[-130.294, 27.473, -242.288]}
        rotation={[Math.PI / 2, 0, -1.135]}
        scale={[1.582, 1.034, 1.582]}
      />

      <mesh
        geometry={nodes["scenery-reflection-on-the-ground-modified"].geometry}
        position={[-99.63, -0.303, -227.178]}
        rotation={[0, 1.135, 0]}
      >
        <meshBasicMaterial map={springVideoTexture} toneMapped={false} />
      </mesh>

      {/* MASKED - TREE TRUNKS */}
      <mesh
        geometry={nodes["tree-trunk-low-poly005"].geometry}
        position={[-234.962, 13.591, -231.239]}
        rotation={[1.127, -1.065, -0.879]}
        scale={1.382}
      >
        <meshStandardMaterial color="#554236" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["tree-trunk-low-poly006"].geometry}
        position={[-249.294, 9.793, -272.146]}
        rotation={[1.246, -0.624, 2.354]}
        scale={2.765}
      >
        <meshStandardMaterial color="#554236" {...stencil} />
      </mesh>

      {/* MASKED - TREE LEAVES, FLOAT PARTICLE LEAVES */}
      <mesh
        geometry={nodes["float-particles005"].geometry}
        position={[-177.39, 11.856, -267.135]}
        rotation={[Math.PI / 2, 0, 0.221]}
        scale={[22.903, 17.377, 16.426]}
      >
        <meshStandardMaterial color="#F8C3CD" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["tree-leaves-low-poly008"].geometry}
        position={[-235.876, 13.134, -231.022]}
        rotation={[1.127, -1.065, -0.879]}
        scale={1.382}
      >
        <meshStandardMaterial color="#F8C3CD" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["tree-leaves-low-poly009"].geometry}
        position={[-250.516, 8.185, -271.605]}
        rotation={[1.246, -0.624, 2.354]}
        scale={2.765}
      >
        <meshStandardMaterial color="#F8C3CD" {...stencil} />
      </mesh>

      {/* MASKED - DIGITAL SCENERY*/}
      <mesh
        geometry={nodes["digital-world"].geometry}
        position={[-197.203, 28.236, -273.315]}
        rotation={[0, 1.135, 0]}
      >
        <meshBasicMaterial
          map={binaryNumbersBackgroundVideo}
          toneMapped={false}
          {...stencil}
        />
      </mesh>

      <mesh
        geometry={nodes.clouds001.geometry}
        position={[-148.329, 32.371, -265.47]}
        rotation={[Math.PI / 2, 0, -0.515]}
        scale={0.063}
      >
        <meshStandardMaterial color="snow" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop005"].geometry}
        position={[-140.273, 45.818, -264.003]}
        rotation={[0, 0.515, 0]}
        scale={[1.31, 1.975, 1.31]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop006"].geometry}
        position={[-141.954, 39.78, -270.418]}
        rotation={[0, 0.515, 0]}
        scale={[1.751, 2.641, 1.751]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop007"].geometry}
        position={[-137.837, 33.323, -267.548]}
        rotation={[0, 0.515, 0]}
        scale={[1.257, 1.896, 1.257]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop008"].geometry}
        position={[-136.296, 25.798, -272.862]}
        rotation={[0, 0.515, 0]}
        scale={[1.31, 1.975, 1.31]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop009"].geometry}
        position={[-140.04, 48.047, -275.076]}
        rotation={[0, 0.515, 0]}
        scale={[1.105, 1.667, 1.105]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>

      <group
        position={[-9.655, 0.704, -116.486]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cube280.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube280_1.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
      </group>
      <group
        position={[-9.655, 0.704, -116.486]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cylinder217.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
        <mesh
          geometry={nodes.Cylinder217_1.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
      </group>
      <mesh
        geometry={nodes["wood-stand004"].geometry}
        material={materials["wood-natural-stand-without-texture"]}
        position={[-9.655, 0.704, -116.486]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      />
      <group
        position={[-9.655, 0.704, -116.486]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cube281.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube281_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <group
        position={[-11.224, 18.904, -107.972]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cube282.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube282_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <group
        position={[-11.402, 20.713, -108.154]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cube283.geometry}
          material={materials["marble-white-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube283_1.geometry}
          material={materials["marble-white-without-texture"]}
        />
      </group>
      <group
        position={[-11.402, 20.713, -108.154]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cube284.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube284_1.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
      </group>
      <group
        position={[-11.402, 20.713, -108.154]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      >
        <mesh
          geometry={nodes.Cube285.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube285_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <group
        position={[-67.621, 9.334, -145.113]}
        rotation={[Math.PI / 2, 0, -3.044]}
        scale={15.467}
      >
        <mesh
          geometry={nodes.PolySphere001.geometry}
          material={materials["stone-material"]}
        />
        <mesh
          geometry={nodes.PolySphere001_1.geometry}
          material={materials["stone-material"]}
        />
      </group>
      <group
        position={[-66.77, 2.31, -145.846]}
        rotation={[-Math.PI, 0.097, -Math.PI]}
        scale={[1.6, 1.6, 16.174]}
      >
        <mesh
          geometry={nodes.Cube286.geometry}
          material={materials["wood-beech"]}
        />
        <mesh
          geometry={nodes.Cube286_1.geometry}
          material={materials["wood-beech"]}
        />
      </group>
      <mesh
        geometry={nodes["stone-support-wood-02001"].geometry}
        material={materials["wood-beech"]}
        position={[-66.77, 2.31, -145.846]}
        rotation={[Math.PI, -1.473, Math.PI]}
        scale={[1.6, 1.6, 16.174]}
      />
      <group
        position={[-66.77, 45.217, -145.846]}
        rotation={[-Math.PI, 0.097, -Math.PI]}
        scale={[4.891, 24.408, 4.891]}
      >
        <mesh
          geometry={nodes.Cylinder219.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cylinder219_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-9.31, 30.098, -79.812]}
        rotation={[1.802, 0.371, -0.347]}
        scale={[-12.22, -1.201, -12.22]}
      >
        <mesh
          geometry={nodes.Cube288.geometry}
          material={materials["marble-white-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube288_1.geometry}
          material={materials["marble-white-without-texture"]}
        />
      </group>
      <group
        position={[-16.856, 49.882, -85.332]}
        rotation={[2.147, -0.312, 1.583]}
        scale={[-12.22, -1.201, -12.22]}
      >
        <mesh
          geometry={nodes.Cube289.geometry}
          material={materials["marble-b-low-poly"]}
        />
        <mesh
          geometry={nodes.Cube289_1.geometry}
          material={materials["marble-b-low-poly"]}
        />
      </group>
      <mesh
        geometry={nodes["wood-cylinder-inside-marble-01001"].geometry}
        material={materials["wood-natural"]}
        position={[-7.593, 30.263, -73.655]}
        rotation={[-1.339, -0.371, -2.795]}
        scale={[1.913, 1.17, 1.913]}
      />
      <mesh
        geometry={nodes["wood-cylinder-inside-marble-02001"].geometry}
        material={materials["wood-natural"]}
        position={[-23.779, 52.31, -80.676]}
        rotation={[-0.995, 0.312, 1.559]}
        scale={[1.913, 1.17, 1.913]}
      />
      <group
        position={[10.015, 40.366, -154.784]}
        rotation={[-0.201, -0.446, 2.842]}
        scale={2.665}
      >
        <mesh
          geometry={nodes.Cube290.geometry}
          material={materials["marble-dark-brown"]}
        />
        <mesh
          geometry={nodes.Cube290_1.geometry}
          material={materials["marble-dark-brown"]}
        />
      </group>
      <group
        position={[1.036, 31.86, -145.669]}
        rotation={[-0.201, -0.446, 1.271]}
        scale={[2.993, 6.188, 1.274]}
      >
        <mesh
          geometry={nodes.Cube291.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube291_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[3.117, 41.641, -149.642]}
        rotation={[0.421, 1.04, -2.124]}
        scale={[2.993, 6.188, 1.274]}
      >
        <mesh
          geometry={nodes.Cube292.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube292_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <mesh
        geometry={nodes["marble-d-3001"].geometry}
        material={materials["marble-brown"]}
        position={[-2.822, 32.792, -143.639]}
        rotation={[0.421, 1.04, 1.018]}
        scale={[1.105, 0.989, 1.105]}
      />
      <mesh
        geometry={nodes["marble-d-2001"].geometry}
        material={materials["marble-white-without-texture"]}
        position={[7.605, 39.965, -150.441]}
        rotation={[-0.201, -0.446, -1.87]}
        scale={[1.105, 0.989, 1.105]}
      />
      <mesh
        geometry={nodes["marble-d-1001"].geometry}
        material={materials["marble-baige"]}
        position={[2.661, 52.999, -145.076]}
        rotation={[0.421, 1.04, 1.018]}
        scale={[1.105, 0.989, 1.105]}
      />
      <group
        position={[6.653, 52.156, -147.059]}
        rotation={[-0.201, -0.446, 1.271]}
        scale={[2.993, 6.188, 1.274]}
      >
        <mesh
          geometry={nodes.Cube293.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube293_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-50.91, 24.388, -103.573]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[6.941, 11.215, 1.996]}
      >
        <mesh
          geometry={nodes.Cube294.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube294_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-48.899, 27.051, -96.862]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[0.89, 11.914, 1.854]}
      >
        <mesh
          geometry={nodes.Cube295.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube295_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials["marble-white-without-texture"]}
        position={[-56.799, 13.288, -98.577]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[1.252, 1.777, 9.317]}
      />
      <mesh
        geometry={nodes["typo-A-backwall001"].geometry}
        material={materials["matt-black"]}
        position={[35.502, 6.078, -193.317]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={[22.526, 37.947, 0.503]}
      />
      <mesh
        geometry={nodes["typo-A-line-horizontal001"].geometry}
        material={materials["matt-white"]}
        position={[33.569, 24.577, -191.983]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={9.519}
      />
      <group
        position={[31.26, 24.577, -190.65]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={9.519}
      >
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials["matt-white"]}
        />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["matt-black"]}
        />
      </group>
      <mesh
        geometry={nodes["typo-A-line-vertical-left001"].geometry}
        material={materials["matt-white"]}
        position={[24.275, 24.577, -197.535]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-A-line-vertical-right001"].geometry}
        material={materials["matt-white"]}
        position={[33.735, 24.577, -181.151]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-backwall001"].geometry}
        material={materials["matt-black"]}
        position={[69.585, 6.078, -195.756]}
        rotation={[0, 1.134, 0]}
        scale={[22.526, 37.947, 0.503]}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-bottom001"].geometry}
        material={materials["matt-white"]}
        position={[74.019, 14.507, -193.888]}
        rotation={[0, 1.134, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-top002"].geometry}
        material={materials["matt-white"]}
        position={[74.534, 34.238, -193.646]}
        rotation={[0, 1.134, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-middle001"].geometry}
        material={materials["matt-white"]}
        position={[74.019, 24.366, -193.888]}
        rotation={[0, 1.134, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-line-vertical001"].geometry}
        material={materials["matt-white"]}
        position={[72.85, 24.577, -183.993]}
        rotation={[0, 1.134, 0]}
        scale={9.519}
      />
      <group
        position={[73.826, 29.333, -199.234]}
        rotation={[0, 1.134, 0]}
        scale={9.938}
      >
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials["matt-black"]}
        />
        <mesh
          geometry={nodes.Circle003_1.geometry}
          material={materials["matt-white"]}
        />
      </group>
      <group
        position={[73.826, 19.395, -199.234]}
        rotation={[0, 1.134, 0]}
        scale={9.938}
      >
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials["matt-black"]}
        />
        <mesh
          geometry={nodes.Circle005_1.geometry}
          material={materials["matt-white"]}
        />
      </group>
      <mesh
        geometry={nodes["typo-C-backwall001"].geometry}
        material={materials["matt-black"]}
        position={[51.445, 6.078, -223.5]}
        rotation={[Math.PI, -0.119, Math.PI]}
        scale={[22.526, 37.947, 0.503]}
      />
      <group
        position={[50.955, 24.578, -225.968]}
        rotation={[Math.PI, -0.119, Math.PI]}
        scale={9.519}
      >
        <mesh
          geometry={nodes.Circle006.geometry}
          material={materials["matt-white"]}
        />
        <mesh
          geometry={nodes.Circle006_1.geometry}
          material={materials["matt-black"]}
        />
      </group>
      <mesh
        geometry={nodes["typo-C-line-horizontal-bottom001"].geometry}
        material={materials["matt-white"]}
        position={[50.616, 15.123, -228.792]}
        rotation={[Math.PI, -0.119, Math.PI]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-C-line-horizontal-top001"].geometry}
        material={nodes["typo-C-line-horizontal-top001"].material}
        position={[50.616, 34.042, -228.792]}
        rotation={[Math.PI, -0.119, Math.PI]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-graphic-wood-stick-bottom001"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[-6.593, 3.171, -242.959]}
        rotation={[Math.PI, 0.19, Math.PI / 2]}
        scale={[-0.418, -16.433, -0.418]}
      />
      <mesh
        geometry={nodes["typo-graphic-textile001"].geometry}
        material={materials["typo-graphic-textile"]}
        position={[-6.544, 26.936, -242.95]}
        rotation={[0, -0.19, Math.PI / 2]}
        scale={0.835}
      />
      <mesh
        geometry={nodes["typo-graphic-wood-stick-top001"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[-6.593, 50.701, -242.959]}
        rotation={[Math.PI, 0.19, Math.PI / 2]}
        scale={[-0.418, -16.433, -0.418]}
      />
      <group
        position={[104.534, 21.083, -378.383]}
        rotation={[0.22, -1.233, -0.277]}
        scale={6.302}
      >
        <mesh
          geometry={nodes.Plane106.geometry}
          material={materials["ceramic-white-cutlery-without-texture"]}
        />
        <mesh
          geometry={nodes.Plane106_1.geometry}
          material={materials["ceramic-black-cutlery-without-texture"]}
        />
      </group>
      <mesh
        geometry={nodes["comforting-dinner-baked-johns003"].geometry}
        material={materials["john-mesh-without-texture"]}
        position={[-111.664, -27.199, -436.06]}
        rotation={[Math.PI / 2, 0, 0.241]}
        scale={100.103}
      />
      <mesh
        ref={comfortingDinnerTextTouch}
        geometry={nodes["text-touch"].geometry}
        material={materials["text-senses"]}
        position={[-110.18, 17.858, -355.142]}
        scale={0.996}
      />
      <mesh
        ref={comfortingDinnerTextSmell}
        geometry={nodes["text-smell"].geometry}
        material={materials["text-senses"]}
        position={[-62.949, 17.858, -401.024]}
        scale={0.996}
      />
      <mesh
        ref={comfortingDinnerTextListen}
        geometry={nodes["text-listen"].geometry}
        material={materials["text-senses"]}
        position={[-0.2, 17.858, -412.494]}
        scale={0.996}
      />
      <mesh
        ref={comfortingDinnerTextLook}
        geometry={nodes["text-look"].geometry}
        material={materials["text-senses"]}
        position={[53.778, 17.858, -371.336]}
        scale={0.996}
      />
      <mesh
        ref={comfortingDinnerTextTaste}
        geometry={nodes["text-taste"].geometry}
        material={materials["text-senses"]}
        position={[63.225, 17.858, -299.14]}
        scale={0.996}
      />
      <mesh
        geometry={nodes["working-desk001"].geometry}
        material={nodes["working-desk001"].material}
        position={[-33.833, 0.134, -7.815]}
        rotation={[0, -1.571, 0]}
        scale={1.476}
      />
      <mesh
        geometry={nodes.chair001.geometry}
        material={nodes.chair001.material}
        position={[-24.225, 0.134, -9.61]}
        rotation={[0, -1.229, 0]}
        scale={10.889}
      />
      <mesh
        geometry={nodes.keyboard001.geometry}
        material={materials.keyboard}
        position={[-34.599, 9.473, -3.294]}
        scale={3.085}
      />
      <mesh
        geometry={nodes.monitor001.geometry}
        material={materials.monitor}
        position={[-34.207, 10.519, -2.958]}
        scale={4.516}
      />
      <mesh
        geometry={nodes["monitor-screen-world"].geometry}
        material={materials["monitor-screen"]}
        position={[-34.118, 10.519, -2.916]}
        scale={4.516}
      />
      <mesh
        geometry={nodes.mouse001.geometry}
        material={materials.mouse}
        position={[-33.065, 9.473, -3.121]}
        rotation={[0, 0.301, 0]}
        scale={3.085}
      />
      <mesh
        geometry={nodes["wall-hanging-shelf-bottom001"].geometry}
        material={nodes["wall-hanging-shelf-bottom001"].material}
        position={[-36.954, 11.963, -28.273]}
        scale={5.398}
      />
      <mesh
        geometry={nodes["wall-hanging-shelf-top001"].geometry}
        material={nodes["wall-hanging-shelf-top001"].material}
        position={[-36.954, 20.706, -28.273]}
        scale={5.398}
      />
      <mesh
        geometry={nodes["presentation-desk-long001"].geometry}
        material={nodes["presentation-desk-long001"].material}
        position={[26.906, 0, 230.452]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.741, 5.566, 5.566]}
      />
      <mesh
        geometry={nodes["presentation-desk-short002"].geometry}
        material={nodes["presentation-desk-short002"].material}
        position={[34.998, 0, 126.634]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.741, 5.566, 5.566]}
      />
      <mesh
        geometry={nodes["presentation-desk-short003"].geometry}
        material={nodes["presentation-desk-short003"].material}
        position={[34.997, 0, 169.945]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.741, 5.566, 5.566]}
      />
      <mesh
        geometry={nodes["monitor-screen-world-pin"].geometry}
        material={materials["monitor-screen-world-pin"]}
        position={[-39.552, 37.235, 42.702]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.599}
      />
      <mesh
        geometry={nodes["monitor-screen-world-pin001"].geometry}
        material={materials["monitor-screen-world-pin"]}
        position={[-39.552, 37.235, 10.235]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.599}
      />
      <mesh
        geometry={nodes["working-desk-workshop003"].geometry}
        material={materials["wood-natural"]}
        position={[-162.852, 0.839, 6.721]}
        rotation={[0, 0.29, 0]}
        scale={6.32}
      />
      <mesh
        geometry={nodes["working-desk-workshop004"].geometry}
        material={materials["wood-natural"]}
        position={[-150.757, 0.839, 3.11]}
        rotation={[0, 0.29, 0]}
        scale={6.32}
      />
      <mesh
        geometry={nodes["sculpture-stand-square-small001"].geometry}
        material={materials["wood-natural"]}
        position={[-141.577, 0.166, 113.432]}
        scale={10.961}
      />
      <mesh
        geometry={nodes["sculpture-stand-round001"].geometry}
        material={materials["wood-natural"]}
        position={[-144.655, 0.839, 72.376]}
        rotation={[0, 0.191, 0]}
        scale={10.726}
      />
      <mesh
        geometry={nodes["sculpture-stand-square-big001"].geometry}
        material={materials["wood-natural"]}
        position={[-165.553, 0.839, 50.039]}
        rotation={[0, -0.091, 0]}
        scale={[19.72, 12.767, 19.72]}
      />
      <mesh
        geometry={nodes["working-desk-workshop005"].geometry}
        material={materials["wood-dark"]}
        position={[-120.599, 0.839, 18.796]}
        scale={6.32}
      />
      <mesh
        geometry={nodes["clay-board001"].geometry}
        material={nodes["clay-board001"].material}
        position={[-127.067, 9.539, 32.429]}
        scale={1.36}
      />
      <mesh
        geometry={nodes.paper001.geometry}
        material={nodes.paper001.material}
        position={[-127.054, 9.126, 46.801]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["clay-in-process-01001"].geometry}
        material={materials.clay}
        position={[-121.226, 10.028, 14.51]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["clay-in-process-02001"].geometry}
        material={materials.clay}
        position={[-119.91, 10.962, 18.568]}
        rotation={[-0.482, -0.017, 0.033]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["sculpture-tool-01001"].geometry}
        material={nodes["sculpture-tool-01001"].material}
        position={[-121.041, 9.304, 6.026]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["sculpture-tool-02001"].geometry}
        material={nodes["sculpture-tool-02001"].material}
        position={[-121.345, 9.291, 7.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.276}
      />
      <mesh
        geometry={nodes["analog-tv-01-modified-square001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-02-modified-horizontal-01001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-horizontal001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-vertical-big001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-vertical-small001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-04-modified-horizontal001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-05-modified-horizontal001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-02-modified-horizontal-02001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-01-modified-square-screen001"].geometry}
        material={materials["analog-tv-01-modified-square-screen"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />

      {/* 3D VISUALS TV SCREENS */}
      <mesh
        geometry={nodes["analog-tv-01-modified-square-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={silkySphereVideoTexture} toneMapped={false} />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-02-modified-horizontal-screen-01001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={dancingTentacleVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={nodes["analog-tv-03-modified-horizontal-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={bloomingFlowerVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-03-modified-vertical-big-screen001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={beautyOfTimePassingVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-03-modified-vertical-small-screen001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={squishyObjectsVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={nodes["analog-tv-04-modified-horizontal-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={sakuraPetalsVideoTexture} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes["analog-tv-05-modified-horizontal-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={glassPoppingVideoTexture} toneMapped={false} />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-02-modified-horizontal-screen-02001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={sequenceRiverVideoTexture} toneMapped={false} />
      </mesh>

      <group
        position={[-156.946, 9.303, 5.166]}
        rotation={[0, 0.29, 0]}
        scale={10.663}
      >
        <mesh geometry={nodes.Cube329.geometry} material={materials.clay} />
        <mesh geometry={nodes.Cube329_1.geometry} material={materials.clay} />
      </group>
      <mesh
        geometry={nodes["sequence-river-water001"].geometry}
        material={materials.clay}
        position={[-156.946, 12.682, 5.166]}
        rotation={[0, 0.29, 0]}
        scale={13.925}
      />
      <mesh
        geometry={nodes["blooming-flower001"].geometry}
        material={materials.clay}
        position={[-142.442, 10.09, 114.37]}
        rotation={[Math.PI / 2, 0, 0.484]}
        scale={3.702}
      />
      <mesh
        geometry={nodes["silky-sphere-low-planer001"].geometry}
        material={materials.clay}
        position={[-144.995, 18.576, 72.331]}
        rotation={[0, 0.191, 0]}
        scale={4.398}
      />
      <group
        position={[-164.339, 15.537, 50.127]}
        rotation={[0, 0.34, 0]}
        scale={19.184}
      >
        <mesh geometry={nodes.Plane109.geometry} material={materials.clay} />
        <mesh geometry={nodes.Plane109_1.geometry} material={materials.clay} />
      </group>
      <mesh
        geometry={nodes["photo-screen001"].geometry}
        material={nodes["photo-screen001"].material}
        position={[-168.374, 14.194, 110.86]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.835, 1.179, 0.835]}
      />
      <mesh
        geometry={nodes["photo-area-support001"].geometry}
        material={nodes["photo-area-support001"].material}
        position={[-168.374, 37.959, 110.93]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[-0.418, -24.35, -0.418]}
      />
      <mesh
        geometry={nodes["spotlight-01001"].geometry}
        material={nodes["spotlight-01001"].material}
        position={[-116.195, 1.078, 78.643]}
        rotation={[1.567, -0.001, 0.733]}
        scale={0.251}
      />
      <mesh
        geometry={nodes["spotlight-02001"].geometry}
        material={nodes["spotlight-02001"].material}
        position={[-154.369, 1.078, 148.606]}
        rotation={[1.575, -0.001, -3.076]}
        scale={0.251}
      />
      <group
        position={[-95.521, 19.483, 112.243]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.633, 0.544, 1.633]}
      >
        <mesh
          geometry={nodes.Cilindro001.geometry}
          material={materials["Dark grey"]}
        />
        <mesh
          geometry={nodes.Cilindro001_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-91.174, 19.19, 112.227]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.017}
      >
        <mesh
          geometry={nodes.camera001.geometry}
          material={materials["Default OBJ.001"]}
        />
        <mesh geometry={nodes.camera001_1.geometry} material={materials.tri} />
      </group>
      <mesh geometry={nodes.room.geometry} material={nodes.room.material} />
      <mesh
        geometry={nodes["picture-frame"].geometry}
        material={materials["picture-frame"]}
        position={[14.09, 21.805, -44.241]}
        scale={1.902}
      />
      <mesh
        geometry={nodes["museum-label"].geometry}
        material={materials["museum-label"]}
        position={[-22.343, 17.058, -46.621]}
        scale={[2.807, 2.807, 4.266]}
      />
      <mesh
        geometry={nodes["gallery-ground"].geometry}
        material={nodes["gallery-ground"].material}
        position={[0, 0, -255.626]}
      />
      <mesh
        geometry={nodes["left-hand-low-poly"].geometry}
        material={materials["human-skin"]}
        position={[-22.627, 2.115, 43.112]}
        rotation={[-2.258, -1.194, -2.383]}
        scale={21.74}
      />
      <mesh
        geometry={nodes["right-hand-low-poly"].geometry}
        material={materials["human-skin"]}
        position={[-12.756, -0.55, 0.029]}
        rotation={[-0.463, -0.963, -0.456]}
        scale={21.74}
      />
    </group>
  );
}

useGLTF.preload("./models/test/stage-test.glb");
