/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/test/stage-test.glb 
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useVideoTexture, Mask, useMask } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";

export default function StageTest(props) {
  /**
   * MASK STENCIL
   */
  const stencil = useMask(1);

  /**
   * VIDEOS FOR THE BEAUTY OF TIME PASSING PROJECT
   */
  const springVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/spring.mp4"
  );
  const summerVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/summer.mp4"
  );
  const autumnVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/autumn.mp4"
  );
  const winterVideoTexture = useVideoTexture(
    "./videos/beauty-of-time-passing/winter.mp4"
  );

  /**
   * VIDEO FOR DIGITAL SCENERY
   */
  const binaryNumbersBackgroundVideo = useVideoTexture(
    "./videos/beauty-of-time-passing/binary-numbers-resize-40perc.mp4"
  );
  binaryNumbersBackgroundVideo.wrapS = THREE.RepeatWrapping;
  binaryNumbersBackgroundVideo.wrapT = THREE.RepeatWrapping;
  binaryNumbersBackgroundVideo.flipY = false;
  binaryNumbersBackgroundVideo.repeat.set(3, 3);

  /**
   * VIDEOS FOR THE 3D VIDUALS
   */
  const silkySphereVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Silkey_Sphere.mp4"
  );

  silkySphereVideoTexture.wrapS = THREE.RepeatWrapping;
  silkySphereVideoTexture.wrapT = THREE.RepeatWrapping;
  silkySphereVideoTexture.flipY = false;

  const bloomingFlowerVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Blooming_Flower.mp4"
  );

  bloomingFlowerVideoTexture.wrapS = THREE.RepeatWrapping;
  bloomingFlowerVideoTexture.wrapT = THREE.RepeatWrapping;
  bloomingFlowerVideoTexture.flipY = false;

  const dancingTentacleVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Dancing_Tentacles.mp4"
  );

  dancingTentacleVideoTexture.wrapS = THREE.RepeatWrapping;
  dancingTentacleVideoTexture.wrapT = THREE.RepeatWrapping;
  dancingTentacleVideoTexture.flipY = false;

  const glassPoppingVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Glass_Popping.mp4"
  );

  glassPoppingVideoTexture.wrapS = THREE.RepeatWrapping;
  glassPoppingVideoTexture.wrapT = THREE.RepeatWrapping;
  glassPoppingVideoTexture.flipY = false;

  const beautyOfTimePassingVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Beauty_Of_Time_Passing.mp4"
  );

  beautyOfTimePassingVideoTexture.wrapS = THREE.RepeatWrapping;
  beautyOfTimePassingVideoTexture.wrapT = THREE.RepeatWrapping;
  beautyOfTimePassingVideoTexture.flipY = false;

  const sakuraPetalsVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Sakura_Petals.mp4"
  );

  sakuraPetalsVideoTexture.wrapS = THREE.RepeatWrapping;
  sakuraPetalsVideoTexture.wrapT = THREE.RepeatWrapping;
  sakuraPetalsVideoTexture.flipY = false;

  const squishyObjectsVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Squishy_Objects.mp4"
  );

  squishyObjectsVideoTexture.wrapS = THREE.RepeatWrapping;
  squishyObjectsVideoTexture.wrapT = THREE.RepeatWrapping;
  squishyObjectsVideoTexture.flipY = false;

  const sequenceRiverVideoTexture = useVideoTexture(
    "./videos/three-d-visuals/Sequence_River.mp4"
  );

  sequenceRiverVideoTexture.wrapS = THREE.RepeatWrapping;
  sequenceRiverVideoTexture.wrapT = THREE.RepeatWrapping;
  sequenceRiverVideoTexture.flipY = false;

  /**
   * MODEL -------------------------------------------------------
   */

  const { nodes, materials } = useGLTF("./models/test/stage-test.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.glassBrick01006.geometry}
        material={materials["glass-low-poly.002"]}
        position={[-185.754, 27.006, -163.713]}
        rotation={[-2.042, 1.319, 0.739]}
        scale={6.188}
      />
      <mesh
        geometry={nodes.glassBrick02006.geometry}
        material={materials["glass-low-poly.002"]}
        position={[-174.442, 18.683, -177.291]}
        rotation={[-Math.PI, 1.327, 2.692]}
        scale={6.188}
      />
      <mesh
        geometry={nodes["led-light-socket003"].geometry}
        material={materials["black-low-poly"]}
        position={[-184.723, 40.932, -164.176]}
        rotation={[-Math.PI, -0.786, 2.712]}
        scale={[36.532, 1.656, 36.532]}
      />
      <mesh
        geometry={nodes["led-light-wire-curve010"].geometry}
        material={materials["black-low-poly"]}
        position={[-187.37, 45.438, -171.033]}
        rotation={[Math.PI / 2, 0, -1.814]}
        scale={7.363}
      />
      <mesh
        geometry={nodes["wood-frame-bottom003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-179.589, 6.983, -173.978]}
        rotation={[Math.PI, -0.243, Math.PI]}
        scale={[3.866, 0.552, 4.433]}
      />
      <mesh
        geometry={nodes["wood-frame-left003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-171.358, 21.749, -157.146]}
        rotation={[0.225, 0.52, -0.113]}
        scale={[3.866, 12.333, 0.552]}
      />
      <mesh
        geometry={nodes["wood-frame-right003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-187.475, 26.981, -187.28]}
        rotation={[2.863, -0.582, 3.071]}
        scale={[3.866, 12.333, 0.552]}
      />
      <mesh
        geometry={nodes["wood-frame-top003"].geometry}
        material={materials["wood-dark-low-poly-without-texture"]}
        position={[-189.641, 46.043, -171.187]}
        rotation={[-0.321, 0.231, -2.575]}
        scale={[3.866, 0.552, 4.433]}
      />
      <mesh
        geometry={nodes["wood-stick-back003"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[-184.262, 13.643, -173.99]}
        rotation={[1.397, 0.043, 3.037]}
        scale={[7.363, 4.97, 7.363]}
      />
      <mesh
        geometry={nodes["wood-stick-front003"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[-177.603, 29.648, -177.556]}
        rotation={[1.823, -0.87, 2.257]}
        scale={[7.363, 4.97, 7.363]}
      />
      <mesh
        geometry={nodes["glass-brick-window-modified"].geometry}
        material={materials["glass-low-poly"]}
        position={[-236.277, 59.454, -110.505]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.605}
      />

      {/* MASK - SCENERY CIRCLE WINDOW */}
      <Mask
        id={1}
        geometry={nodes["scenery-window-mask"].geometry}
        position={[-99.46, 27.759, -323.571]}
        rotation={[Math.PI / 2, 0, -0.561]}
        scale={7.427}
      >
        <meshBasicMaterial />
      </Mask>

      <group
        position={[-98.828, 28.155, -323.036]}
        rotation={[0, 0.561, 0]}
        scale={34.481}
      >
        <mesh
          geometry={nodes.Plane110.geometry}
          material={materials["black-low-poly"]}
        />
        <mesh
          geometry={nodes.Plane110_1.geometry}
          material={materials["paper-screen-white"]}
        />
      </group>

      <mesh
        geometry={nodes["circle-window-frame"].geometry}
        material={materials["black-low-poly"]}
        position={[-97.401, 27.473, -320.132]}
        rotation={[Math.PI / 2, 0, -0.561]}
        scale={[1.582, 1.034, 1.582]}
      />

      <mesh
        geometry={nodes["scenery-reflection-on-the-ground-modified"].geometry}
        position={[-79.845, -0.303, -290.799]}
        rotation={[0, 0.561, 0]}
      >
        <meshBasicMaterial map={springVideoTexture} toneMapped={false} />
      </mesh>

      {/* MASKED - TREE TRUNKS */}
      <mesh
        geometry={nodes["tree-trunk-low-poly005"].geometry}
        position={[-191.31, 13.591, -367.654]}
        rotation={[2.172, -1.012, 0.3]}
        scale={1.382}
      >
        <meshStandardMaterial color="#554236" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["tree-trunk-low-poly006"].geometry}
        position={[-181.148, 9.793, -409.791]}
        rotation={[1.7, -0.683, 3.08]}
        scale={2.765}
      >
        <meshStandardMaterial color="#554236" {...stencil} />
      </mesh>

      {/* MASKED - TREE LEAVES, FLOAT PARTICLE LEAVES */}
      <mesh
        geometry={nodes["float-particles005"].geometry}
        position={[-123.473, 11.856, -366.56]}
        rotation={[Math.PI / 2, 0, 0.795]}
        scale={[22.903, 17.377, 16.426]}
      >
        <meshStandardMaterial color="#F8C3CD" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["tree-leaves-low-poly008"].geometry}
        position={[-192.196, 13.134, -367.968]}
        rotation={[2.172, -1.012, 0.3]}
        scale={1.382}
      >
        <meshStandardMaterial color="#F8C3CD" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["tree-leaves-low-poly009"].geometry}
        position={[-182.467, 8.185, -410]}
        rotation={[1.7, -0.683, 3.08]}
        scale={2.765}
      >
        <meshStandardMaterial color="#F8C3CD" {...stencil} />
      </mesh>

      {/* MASKED - DIGITAL SCENERY*/}
      <mesh
        geometry={nodes["digital-world"].geometry}
        position={[-136.76, 28.236, -382.503]}
        rotation={[0, 0.561, 0]}
      >
        <meshBasicMaterial
          map={binaryNumbersBackgroundVideo}
          toneMapped={false}
          {...stencil}
        />
      </mesh>

      <mesh
        geometry={nodes.clouds001.geometry}
        position={[-99.967, 32.371, -349.39]}
        rotation={[Math.PI / 2, 0, 0.059]}
        scale={0.063}
      >
        <meshStandardMaterial color="snow" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop005"].geometry}
        position={[-93.997, 45.818, -343.786]}
        rotation={[0, -0.059, 0]}
        scale={[1.31, 1.975, 1.31]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop006"].geometry}
        position={[-91.927, 39.78, -350.086]}
        rotation={[0, -0.059, 0]}
        scale={[1.751, 2.641, 1.751]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop007"].geometry}
        position={[-90.028, 33.323, -345.442]}
        rotation={[0, -0.059, 0]}
        scale={[1.257, 1.896, 1.257]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop008"].geometry}
        position={[-85.849, 25.798, -349.069]}
        rotation={[0, -0.059, 0]}
        scale={[1.31, 1.975, 1.31]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>
      <mesh
        geometry={nodes["rain-drop009"].geometry}
        position={[-87.793, 48.047, -352.96]}
        rotation={[0, -0.059, 0]}
        scale={[1.105, 1.667, 1.105]}
      >
        <meshStandardMaterial color="#81C7D4" {...stencil} />
      </mesh>

      <group
        position={[-38.566, 0.392, -166.947]}
        rotation={[0.134, -0.786, 0.201]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cube280.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube280_1.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
      </group>
      <group
        position={[-38.566, 0.392, -166.947]}
        rotation={[0.134, -0.786, 0.201]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cylinder217.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
        <mesh
          geometry={nodes.Cylinder217_1.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
      </group>
      <mesh
        geometry={nodes["wood-stand004"].geometry}
        material={materials["wood-natural-stand-without-texture"]}
        position={[-38.566, 0.392, -166.947]}
        rotation={[0.134, -0.786, 0.201]}
        scale={1.268}
      />
      <group
        position={[-38.566, 0.392, -166.947]}
        rotation={[0.134, -0.786, 0.201]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cube281.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube281_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <group
        position={[-39.518, 11.442, -161.778]}
        rotation={[2.914, -1.225, 3.004]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cube282.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube282_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <group
        position={[-39.627, 12.54, -161.889]}
        rotation={[2.914, -1.225, 3.004]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cube283.geometry}
          material={materials["marble-white-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube283_1.geometry}
          material={materials["marble-white-without-texture"]}
        />
      </group>
      <group
        position={[-39.627, 12.54, -161.889]}
        rotation={[2.914, -1.225, 3.004]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cube284.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube284_1.geometry}
          material={materials["wood-natural-stand-without-texture"]}
        />
      </group>
      <group
        position={[-39.627, 12.54, -161.889]}
        rotation={[2.914, -1.225, 3.004]}
        scale={1.268}
      >
        <mesh
          geometry={nodes.Cube285.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube285_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <group
        position={[-95.276, 6.494, -106.42]}
        rotation={[Math.PI / 2, 0, -3.044]}
        scale={9.912}
      >
        <mesh
          geometry={nodes.PolySphere001.geometry}
          material={materials["stone-material"]}
        />
        <mesh
          geometry={nodes.PolySphere001_1.geometry}
          material={materials["stone-material"]}
        />
      </group>
      <group
        position={[-94.731, 1.993, -106.889]}
        rotation={[-Math.PI, 0.097, -Math.PI]}
        scale={[1.025, 1.025, 10.365]}
      >
        <mesh
          geometry={nodes.Cube286.geometry}
          material={materials["wood-beech"]}
        />
        <mesh
          geometry={nodes.Cube286_1.geometry}
          material={materials["wood-beech"]}
        />
      </group>
      <mesh
        geometry={nodes["stone-support-wood-02001"].geometry}
        material={materials["wood-beech"]}
        position={[-94.731, 1.993, -106.889]}
        rotation={[Math.PI, -1.473, Math.PI]}
        scale={[1.025, 1.025, 10.365]}
      />
      <group
        position={[-94.731, 29.49, -106.889]}
        rotation={[-Math.PI, 0.097, -Math.PI]}
        scale={[3.134, 15.642, 3.134]}
      >
        <mesh
          geometry={nodes.Cylinder219.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cylinder219_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-38.356, 18.238, -144.681]}
        rotation={[1.802, 0.371, -0.347]}
        scale={[-7.419, -0.729, -7.419]}
      >
        <mesh
          geometry={nodes.Cube288.geometry}
          material={materials["marble-white-without-texture"]}
        />
        <mesh
          geometry={nodes.Cube288_1.geometry}
          material={materials["marble-white-without-texture"]}
        />
      </group>
      <group
        position={[-42.938, 30.25, -148.032]}
        rotation={[2.147, -0.312, 1.583]}
        scale={[-7.419, -0.729, -7.419]}
      >
        <mesh
          geometry={nodes.Cube289.geometry}
          material={materials["marble-b-low-poly"]}
        />
        <mesh
          geometry={nodes.Cube289_1.geometry}
          material={materials["marble-b-low-poly"]}
        />
      </group>
      <mesh
        geometry={nodes["wood-cylinder-inside-marble-01001"].geometry}
        material={materials["wood-natural"]}
        position={[-37.314, 18.338, -140.943]}
        rotation={[-1.339, -0.371, -2.795]}
        scale={[1.161, 0.711, 1.161]}
      />
      <mesh
        geometry={nodes["wood-cylinder-inside-marble-02001"].geometry}
        material={materials["wood-natural"]}
        position={[-47.141, 31.725, -145.205]}
        rotation={[-0.995, 0.312, 1.559]}
        scale={[1.161, 0.711, 1.161]}
      />
      <group
        position={[-26.623, 24.473, -190.2]}
        rotation={[-0.201, -0.446, 2.842]}
        scale={1.618}
      >
        <mesh
          geometry={nodes.Cube290.geometry}
          material={materials["marble-dark-brown"]}
        />
        <mesh
          geometry={nodes.Cube290_1.geometry}
          material={materials["marble-dark-brown"]}
        />
      </group>
      <group
        position={[-32.075, 19.309, -184.666]}
        rotation={[-0.201, -0.446, 1.271]}
        scale={[1.817, 3.757, 0.773]}
      >
        <mesh
          geometry={nodes.Cube291.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube291_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-30.811, 25.247, -187.078]}
        rotation={[0.421, 1.04, -2.124]}
        scale={[1.817, 3.757, 0.773]}
      >
        <mesh
          geometry={nodes.Cube292.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube292_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <mesh
        geometry={nodes["marble-d-3001"].geometry}
        material={materials["marble-brown"]}
        position={[-34.418, 19.874, -183.434]}
        rotation={[0.421, 1.04, 1.018]}
        scale={[0.671, 0.6, 0.671]}
      />
      <mesh
        geometry={nodes["marble-d-2001"].geometry}
        material={materials["marble-white-without-texture"]}
        position={[-28.086, 24.229, -187.563]}
        rotation={[-0.201, -0.446, -1.87]}
        scale={[0.671, 0.6, 0.671]}
      />
      <mesh
        geometry={nodes["marble-d-1001"].geometry}
        material={materials["marble-baige"]}
        position={[-31.089, 32.143, -184.306]}
        rotation={[0.421, 1.04, 1.018]}
        scale={[0.671, 0.6, 0.671]}
      />
      <group
        position={[-28.665, 31.631, -185.51]}
        rotation={[-0.201, -0.446, 1.271]}
        scale={[1.817, 3.757, 0.773]}
      >
        <mesh
          geometry={nodes.Cube293.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube293_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-63.614, 14.772, -159.108]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[4.214, 6.809, 1.212]}
      >
        <mesh
          geometry={nodes.Cube294.geometry}
          material={materials["wood-natural"]}
        />
        <mesh
          geometry={nodes.Cube294_1.geometry}
          material={materials["wood-natural"]}
        />
      </group>
      <group
        position={[-62.393, 16.388, -155.033]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[0.541, 7.234, 1.126]}
      >
        <mesh
          geometry={nodes.Cube295.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
        <mesh
          geometry={nodes.Cube295_1.geometry}
          material={materials["marble-black-witouth-texture"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials["marble-white-without-texture"]}
        position={[-67.189, 8.032, -156.074]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[0.76, 1.079, 5.657]}
      />
      <mesh
        geometry={nodes["typo-A-backwall001"].geometry}
        material={materials["matt-black"]}
        position={[108.811, 6.078, -238.9]}
        rotation={[0, -1.571, 0]}
        scale={[22.526, 37.947, 0.503]}
      />
      <mesh
        geometry={nodes["typo-A-line-horizontal001"].geometry}
        material={materials["matt-white"]}
        position={[106.47, 24.577, -238.711]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <group
        position={[103.804, 24.577, -238.711]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      >
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials["matt-white"]}
        />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["matt-black"]}
        />
      </group>
      <mesh
        geometry={nodes["typo-A-line-vertical-left001"].geometry}
        material={materials["matt-white"]}
        position={[101.198, 24.577, -248.167]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-A-line-vertical-right001"].geometry}
        material={materials["matt-white"]}
        position={[101.198, 24.577, -229.247]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-backwall001"].geometry}
        material={materials["matt-black"]}
        position={[108.811, 6.078, -182.848]}
        rotation={[0, -1.571, 0]}
        scale={[22.526, 37.947, 0.503]}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-bottom001"].geometry}
        material={materials["matt-white"]}
        position={[104.004, 14.507, -182.659]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-top002"].geometry}
        material={materials["matt-white"]}
        position={[103.435, 34.238, -182.659]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-middle001"].geometry}
        material={materials["matt-white"]}
        position={[104.004, 24.366, -182.659]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-B-line-vertical001"].geometry}
        material={materials["matt-white"]}
        position={[100.865, 24.577, -192.114]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <group
        position={[106.446, 29.333, -177.9]}
        rotation={[0, -1.571, 0]}
        scale={9.938}
      >
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials["matt-black"]}
        />
        <mesh
          geometry={nodes.Circle003_1.geometry}
          material={materials["matt-white"]}
        />
      </group>
      <group
        position={[106.446, 19.395, -177.9]}
        rotation={[0, -1.571, 0]}
        scale={9.938}
      >
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials["matt-black"]}
        />
        <mesh
          geometry={nodes.Circle005_1.geometry}
          material={materials["matt-white"]}
        />
      </group>
      <mesh
        geometry={nodes["typo-C-backwall001"].geometry}
        material={materials["matt-black"]}
        position={[108.811, 6.078, -125.922]}
        rotation={[0, -1.571, 0]}
        scale={[22.526, 37.947, 0.503]}
      />
      <group
        position={[106.302, 24.578, -125.73]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      >
        <mesh
          geometry={nodes.Circle006.geometry}
          material={materials["matt-white"]}
        />
        <mesh
          geometry={nodes.Circle006_1.geometry}
          material={materials["matt-black"]}
        />
      </group>
      <mesh
        geometry={nodes["typo-C-line-horizontal-bottom001"].geometry}
        material={materials["matt-white"]}
        position={[103.458, 15.123, -125.73]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-C-line-horizontal-top001"].geometry}
        material={nodes["typo-C-line-horizontal-top001"].material}
        position={[103.458, 34.042, -125.73]}
        rotation={[0, -1.571, 0]}
        scale={9.519}
      />
      <mesh
        geometry={nodes["typo-graphic-wood-stick-bottom001"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[46.07, 3.171, -245.017]}
        rotation={[-Math.PI, 0.961, Math.PI / 2]}
        scale={[-0.418, -16.433, -0.418]}
      />
      <mesh
        geometry={nodes["typo-graphic-textile001"].geometry}
        material={materials["typo-graphic-textile"]}
        position={[46.099, 26.936, -244.976]}
        rotation={[0, -0.961, Math.PI / 2]}
        scale={0.835}
      />
      <mesh
        geometry={nodes["typo-graphic-wood-stick-top001"].geometry}
        material={materials["wood-natural-low-poly"]}
        position={[46.07, 50.701, -245.017]}
        rotation={[-Math.PI, 0.961, Math.PI / 2]}
        scale={[-0.418, -16.433, -0.418]}
      />
      <group
        position={[121.882, 12.936, -441.17]}
        rotation={[0.22, -1.233, -0.277]}
        scale={5.045}
      >
        <mesh
          geometry={nodes.Plane106.geometry}
          material={materials["ceramic-white-cutlery-without-texture"]}
        />
        <mesh
          geometry={nodes.Plane106_1.geometry}
          material={materials["ceramic-black-cutlery-without-texture"]}
        />
      </group>
      <mesh
        geometry={nodes["comforting-dinner-baked-johns003"].geometry}
        material={materials["john-mesh-without-texture"]}
        position={[-51.202, -25.718, -487.344]}
        rotation={[Math.PI / 2, 0, 0.241]}
        scale={80.141}
      />
      <mesh
        geometry={nodes["working-desk001"].geometry}
        material={nodes["working-desk001"].material}
        position={[-33.833, 0.134, -7.815]}
        rotation={[0, -1.571, 0]}
        scale={1.476}
      />
      <mesh
        geometry={nodes.chair001.geometry}
        material={nodes.chair001.material}
        position={[-24.225, 0.134, -9.61]}
        rotation={[0, -1.229, 0]}
        scale={10.889}
      />
      <mesh
        geometry={nodes.keyboard001.geometry}
        material={materials.keyboard}
        position={[-34.599, 9.473, -3.294]}
        scale={3.085}
      />
      <mesh
        geometry={nodes.monitor001.geometry}
        material={materials.monitor}
        position={[-34.207, 10.519, -2.958]}
        scale={4.516}
      />
      <mesh
        geometry={nodes["monitor-screen-world"].geometry}
        material={materials["monitor-screen"]}
        position={[-34.118, 10.519, -2.916]}
        scale={4.516}
      />
      <mesh
        geometry={nodes.mouse001.geometry}
        material={materials.mouse}
        position={[-33.065, 9.473, -3.121]}
        rotation={[0, 0.301, 0]}
        scale={3.085}
      />
      <mesh
        geometry={nodes["wall-hanging-shelf-bottom001"].geometry}
        material={nodes["wall-hanging-shelf-bottom001"].material}
        position={[-36.954, 11.963, -28.273]}
        scale={5.398}
      />
      <mesh
        geometry={nodes["wall-hanging-shelf-top001"].geometry}
        material={nodes["wall-hanging-shelf-top001"].material}
        position={[-36.954, 20.706, -28.273]}
        scale={5.398}
      />
      <mesh
        geometry={nodes["presentation-desk-long001"].geometry}
        material={nodes["presentation-desk-long001"].material}
        position={[28.454, 0, 214.736]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[3.38, 3.969, 3.969]}
      />
      <mesh
        geometry={nodes["presentation-desk-short002"].geometry}
        material={nodes["presentation-desk-short002"].material}
        position={[34.224, 0, 140.706]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[3.38, 3.969, 3.969]}
      />
      <mesh
        geometry={nodes["presentation-desk-short003"].geometry}
        material={nodes["presentation-desk-short003"].material}
        position={[34.223, 0, 171.59]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[3.38, 3.969, 3.969]}
      />
      <mesh
        geometry={nodes["monitor-screen-world-pin"].geometry}
        material={materials["monitor-screen-world-pin"]}
        position={[-39.552, 37.235, 42.702]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.599}
      />
      <mesh
        geometry={nodes["monitor-screen-world-pin001"].geometry}
        material={materials["monitor-screen-world-pin"]}
        position={[-39.552, 37.235, 10.235]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.599}
      />
      <mesh
        geometry={nodes["working-desk-workshop003"].geometry}
        material={nodes["working-desk-workshop003"].material}
        position={[-162.852, 0.839, 6.721]}
        rotation={[0, 0.29, 0]}
        scale={6.32}
      />
      <mesh
        geometry={nodes["working-desk-workshop004"].geometry}
        material={nodes["working-desk-workshop004"].material}
        position={[-150.757, 0.839, 3.11]}
        rotation={[0, 0.29, 0]}
        scale={6.32}
      />
      <mesh
        geometry={nodes["sculpture-stand-square-small001"].geometry}
        material={nodes["sculpture-stand-square-small001"].material}
        position={[-141.577, 0.166, 113.432]}
        scale={10.961}
      />
      <mesh
        geometry={nodes["sculpture-stand-round001"].geometry}
        material={nodes["sculpture-stand-round001"].material}
        position={[-144.655, 0.839, 72.376]}
        rotation={[0, 0.191, 0]}
        scale={10.726}
      />
      <mesh
        geometry={nodes["sculpture-stand-square-big001"].geometry}
        material={nodes["sculpture-stand-square-big001"].material}
        position={[-165.553, 0.839, 50.039]}
        rotation={[0, -0.091, 0]}
        scale={[19.72, 12.767, 19.72]}
      />
      <mesh
        geometry={nodes["working-desk-workshop005"].geometry}
        material={nodes["working-desk-workshop005"].material}
        position={[-120.599, 0.839, 18.796]}
        scale={6.32}
      />
      <mesh
        geometry={nodes["clay-board001"].geometry}
        material={nodes["clay-board001"].material}
        position={[-127.067, 9.539, 32.429]}
        scale={1.36}
      />
      <mesh
        geometry={nodes.paper001.geometry}
        material={nodes.paper001.material}
        position={[-127.054, 9.126, 46.801]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["clay-in-process-01001"].geometry}
        material={nodes["clay-in-process-01001"].material}
        position={[-121.226, 10.028, 14.51]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["clay-in-process-02001"].geometry}
        material={nodes["clay-in-process-02001"].material}
        position={[-119.91, 10.962, 18.568]}
        rotation={[-0.482, -0.017, 0.033]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["sculpture-tool-01001"].geometry}
        material={nodes["sculpture-tool-01001"].material}
        position={[-121.041, 9.304, 6.026]}
        scale={1.36}
      />
      <mesh
        geometry={nodes["sculpture-tool-02001"].geometry}
        material={nodes["sculpture-tool-02001"].material}
        position={[-121.345, 9.291, 7.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.276}
      />
      <mesh
        geometry={nodes["analog-tv-01-modified-square001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-02-modified-horizontal-01001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-horizontal001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-vertical-big001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-vertical-small001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-04-modified-horizontal001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-05-modified-horizontal001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />
      <mesh
        geometry={nodes["analog-tv-02-modified-horizontal-02001"].geometry}
        material={materials["analog-tv-black-matt"]}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      />

      {/* 3D VISUALS TV SCREENS */}
      <mesh
        geometry={nodes["analog-tv-01-modified-square-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={silkySphereVideoTexture} toneMapped={false} />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-02-modified-horizontal-screen-01001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={dancingTentacleVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={nodes["analog-tv-03-modified-horizontal-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={bloomingFlowerVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-03-modified-vertical-big-screen001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={beautyOfTimePassingVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-03-modified-vertical-small-screen001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial
          map={squishyObjectsVideoTexture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={nodes["analog-tv-04-modified-horizontal-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={sakuraPetalsVideoTexture} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes["analog-tv-05-modified-horizontal-screen001"].geometry}
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={glassPoppingVideoTexture} toneMapped={false} />
      </mesh>
      <mesh
        geometry={
          nodes["analog-tv-02-modified-horizontal-screen-02001"].geometry
        }
        position={[-194.784, 0, 11.666]}
        rotation={[-Math.PI, 0.791, -Math.PI]}
      >
        <meshBasicMaterial map={sequenceRiverVideoTexture} toneMapped={false} />
      </mesh>

      <group
        position={[-156.946, 9.303, 5.166]}
        rotation={[0, 0.29, 0]}
        scale={10.663}
      >
        <mesh
          geometry={nodes.Cube329.geometry}
          material={nodes.Cube329.material}
        />
        <mesh
          geometry={nodes.Cube329_1.geometry}
          material={nodes.Cube329_1.material}
        />
      </group>
      <mesh
        geometry={nodes["sequence-river-water001"].geometry}
        material={nodes["sequence-river-water001"].material}
        position={[-156.946, 12.682, 5.166]}
        rotation={[0, 0.29, 0]}
        scale={13.925}
      />
      <mesh
        geometry={nodes["blooming-flower001"].geometry}
        material={materials["Default OBJ"]}
        position={[-142.442, 10.09, 114.37]}
        rotation={[Math.PI / 2, 0, 0.484]}
        scale={3.702}
      />
      <mesh
        geometry={nodes["silky-sphere-low-planer001"].geometry}
        material={nodes["silky-sphere-low-planer001"].material}
        position={[-144.995, 18.576, 72.331]}
        rotation={[0, 0.191, 0]}
        scale={4.398}
      />
      <group
        position={[-164.339, 15.537, 50.127]}
        rotation={[0, 0.34, 0]}
        scale={19.184}
      >
        <mesh
          geometry={nodes.Plane109.geometry}
          material={nodes.Plane109.material}
        />
        <mesh
          geometry={nodes.Plane109_1.geometry}
          material={nodes.Plane109_1.material}
        />
      </group>
      <mesh
        geometry={nodes["photo-screen001"].geometry}
        material={nodes["photo-screen001"].material}
        position={[-168.374, 14.194, 110.86]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.835, 1.179, 0.835]}
      />
      <mesh
        geometry={nodes["photo-area-support001"].geometry}
        material={nodes["photo-area-support001"].material}
        position={[-168.374, 37.959, 110.93]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[-0.418, -24.35, -0.418]}
      />
      <mesh
        geometry={nodes["spotlight-01001"].geometry}
        material={nodes["spotlight-01001"].material}
        position={[-116.195, 1.078, 78.643]}
        rotation={[1.567, -0.001, 0.733]}
        scale={0.251}
      />
      <mesh
        geometry={nodes["spotlight-02001"].geometry}
        material={nodes["spotlight-02001"].material}
        position={[-154.369, 1.078, 148.606]}
        rotation={[1.575, -0.001, -3.076]}
        scale={0.251}
      />
      <group
        position={[-95.521, 19.483, 112.243]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.633, 0.544, 1.633]}
      >
        <mesh
          geometry={nodes.Cilindro001.geometry}
          material={materials["Dark grey"]}
        />
        <mesh
          geometry={nodes.Cilindro001_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-91.174, 19.19, 112.227]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.017}
      >
        <mesh
          geometry={nodes.camera001.geometry}
          material={materials["Default OBJ.001"]}
        />
        <mesh geometry={nodes.camera001_1.geometry} material={materials.tri} />
      </group>
      <mesh geometry={nodes.room.geometry} material={nodes.room.material} />
      <mesh
        geometry={nodes["picture-frame"].geometry}
        material={materials["picture-frame"]}
        position={[14.09, 21.805, -44.241]}
        scale={1.902}
      />
      <mesh
        geometry={nodes["museum-label"].geometry}
        material={materials["museum-label"]}
        position={[-22.343, 17.058, -46.621]}
        scale={[2.807, 2.807, 4.266]}
      />
      <mesh
        geometry={nodes["gallery-ground"].geometry}
        material={nodes["gallery-ground"].material}
        position={[0, 0, -255.626]}
      />
      <mesh
        geometry={nodes["left-hand-low-poly"].geometry}
        material={nodes["left-hand-low-poly"].material}
        position={[-22.627, 2.115, 43.112]}
        rotation={[-2.258, -1.194, -2.383]}
        scale={21.74}
      />
      <mesh
        geometry={nodes["right-hand-low-poly"].geometry}
        material={nodes["right-hand-low-poly"].material}
        position={[-12.756, -0.55, 0.029]}
        rotation={[-0.463, -0.963, -0.456]}
        scale={21.74}
      />
    </group>
  );
}

useGLTF.preload("./models/test/stage-test.glb");
