/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/meteoroids/meteoroid_01.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { fadeOnBeforeCompile } from "../../../utils/fadeMaterial";

export default function Meteoroid({ opacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/meteoroids/meteoroid_01.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        scale={3.5}
        geometry={nodes.meteoroid_01.geometry}
        // material={materials["plane-white-planet-material"]}
      >
        <meshStandardMaterial
          onBeforeCompile={fadeOnBeforeCompile}
          opacity={opacity}
          transparent={true}
          envMapIntensity={2}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/meteoroids/meteoroid_01.glb");
