/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/design-works/beauty-of-time-passing/beauty-of-time-passing.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/beauty-of-time-passing.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['scenery-window-spring'].geometry} material={materials['emission-plane-pink']} />
      <mesh geometry={nodes.wall004.geometry} material={materials['wood-natural-wall']} />
      <mesh geometry={nodes['scenery-window-summer'].geometry} material={materials['emission-plane-green']} />
      <mesh geometry={nodes['scenery-window-fall'].geometry} material={materials['emission-plane-red']} />
      <mesh geometry={nodes['scenery-window-winter'].geometry} material={materials['emission-plane-white']} />
    </group>
  )
}

useGLTF.preload('/beauty-of-time-passing.glb')
