/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/glass-lens-objects/glass-lens-objects.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/glass-lens-objects.glb");
  return (

  );
}

useGLTF.preload("/glass-lens-objects.glb");
