/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/pop-tiles/pop-tiles.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/pop-tiles.glb");
  return (
    <group {...props} dispose={null}>
        {/* 1. Ambience of Light */}
        <group ref={(element) => (popTiles.current[0] = element)}>
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube005_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-001-image"].geometry}
          material={nodes["pop-title-001-image"].material}
        />
      </group>

      {/* 2. Beauty of Time Passing */}
      <group ref={(element) => (popTiles.current[1] = element)}>
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube023_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-002-image"].geometry}
          material={nodes["pop-title-002-image"].material}
        />
      </group>

      {/* 3. Interevention in our Disconnection */}
      <group ref={(element) => (popTiles.current[2] = element)}>
        <mesh
          geometry={nodes.Cube029.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube029_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube029_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-003-image"].geometry}
          material={nodes["pop-title-003-image"].material}
        />
      </group>

      {/* 4. Masu Typo */}
      <group ref={(element) => (popTiles.current[3] = element)}>
        <mesh
          geometry={nodes.Cube035.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube035_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube035_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-004-image"].geometry}
          material={nodes["pop-title-004-image"].material}
        />
      </group>

      {/* 5. Comforting Dinner */}
      <group ref={(element) => (popTiles.current[4] = element)}>
        <mesh
          geometry={nodes.Cube041.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube041_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube041_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-005-image"].geometry}
          material={nodes["pop-title-005-image"].material}
        />
      </group>

      {/* 6. 3D Visuals */}
      <group ref={(element) => (popTiles.current[5] = element)}>
        <mesh
          geometry={nodes.Cube047.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube047_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube047_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-006-image"].geometry}
          material={nodes["pop-title-006-image"].material}
        />
      </group>

      {/* 7. Portfolio Website */}
      <group ref={(element) => (popTiles.current[6] = element)}>
        <mesh
          geometry={nodes.Cube053.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube053_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube053_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-007-image"].geometry}
          material={nodes["pop-title-007-image"].material}
        />
      </group>

      {/* 8. OBJECT Rotterdam 2024 */}
      <group ref={(element) => (popTiles.current[7] = element)}>
        <mesh
          geometry={nodes.Cube059.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube059_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube059_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-008-image"].geometry}
          material={nodes["pop-title-008-image"].material}
        />
      </group>

      {/* 9. Weather Cereal */}
      <group ref={(element) => (popTiles.current[8] = element)}>
        <mesh
          geometry={nodes.Cube065.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube065_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube065_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-009-image"].geometry}
          material={nodes["pop-title-009-image"].material}
        />
      </group>

      {/* 10. Donuts Universe */}
      <group ref={(element) => (popTiles.current[9] = element)}>
        <mesh
          geometry={nodes.Cube071.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube071_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube071_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-010-image"].geometry}
          material={nodes["pop-title-010-image"].material}
        />
      </group>

      {/* 11. Marble's on a Roll */}
      <group ref={(element) => (popTiles.current[10] = element)}>
        <mesh
          geometry={nodes.Cube077.geometry}
          material={materials["pop-tile-top.001"]}
        />
        <mesh
          geometry={nodes.Cube077_1.geometry}
          material={materials["pop-tile-hanging-wires"]}
        />
        <mesh
          geometry={nodes.Cube077_2.geometry}
          material={materials["pop-tile-glass-case"]}
        />
        <mesh
          geometry={nodes["pop-title-011-image"].geometry}
          material={nodes["pop-title-011-image"].material}
        />
      </group>

      {/* GROUND */}
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["pop-tile-ground"]}
      />
      <mesh
        geometry={nodes.Cube016_1.geometry}
        material={materials["pop-tile-emission-hole"]}
      />
      
    </group>
  );
}

useGLTF.preload("/pop-tiles.glb");
