/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/test/stage-test.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function StageTest(props) {
  const { nodes, materials } = useGLTF('/models/test/stage-test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube145.geometry} material={materials['black-glossy-floor']} />
      <mesh geometry={nodes.Cube145_1.geometry} material={materials['low-poly-human']} />
      <mesh geometry={nodes.Cube145_2.geometry} material={materials['wood-natural-low-poly']} />
      <mesh geometry={nodes.Cube145_3.geometry} material={materials['wood-dark-low-poly.001']} />
      <mesh geometry={nodes.Cube145_4.geometry} material={materials['black-low-poly.002']} />
      <mesh geometry={nodes.Cube145_5.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.Cube145_6.geometry} material={materials['black-low-poly']} />
      <mesh geometry={nodes.Cube145_7.geometry} material={materials['emission-plane-pink']} />
      <mesh geometry={nodes.Cube145_8.geometry} material={materials['emission-plane-green']} />
      <mesh geometry={nodes.Cube145_9.geometry} material={materials['emission-plane-red']} />
      <mesh geometry={nodes.Cube145_10.geometry} material={materials['emission-plane-white']} />
    </group>
  )
}

useGLTF.preload('/models/test/stage-test.glb')
