/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Astronout(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/astronout/astronout.gltf"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Flying"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[0, -1.0, 0]}>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="astronaut001">
            <skinnedMesh
              name="Cube009"
              geometry={nodes.Cube009.geometry}
              material={materials["material-space-suit-body.001"]}
              skeleton={nodes.Cube009.skeleton}
            />
            <skinnedMesh
              name="Cube009_1"
              geometry={nodes.Cube009_1.geometry}
              material={materials["material-space-suit-red-accent.001"]}
              skeleton={nodes.Cube009_1.skeleton}
            />
            <skinnedMesh
              name="Cube009_2"
              geometry={nodes.Cube009_2.geometry}
              material={materials["material-space-suit-face-cover.001"]}
              skeleton={nodes.Cube009_2.skeleton}
            />
          </group>
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/astronout/astronout.gltf");
