/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/new-atelier/new-atelier-mono.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function NewAtelierMono(props) {
  const { nodes, materials } = useGLTF("/models/new-atelier/new-atelier-mono.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["icon-html001"].geometry}
        material={nodes["icon-html001"].material}
        position={[-36.979, 76.277, -21.214]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-css001"].geometry}
        material={nodes["icon-css001"].material}
        position={[-36.979, 76.746, -33.293]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-javascript001"].geometry}
        material={nodes["icon-javascript001"].material}
        position={[-36.979, 76.467, -45.373]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-react001"].geometry}
        material={nodes["icon-react001"].material}
        position={[-36.979, 76.584, -57.027]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-three-js001"].geometry}
        material={nodes["icon-three-js001"].material}
        position={[-36.979, 58.591, -20.871]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-blender001"].geometry}
        material={nodes["icon-blender001"].material}
        position={[-36.979, 57.564, -33.098]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-houdini001"].geometry}
        material={nodes["icon-houdini001"].material}
        position={[-36.979, 57.872, -44.467]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-unreal-engine001"].geometry}
        material={nodes["icon-unreal-engine001"].material}
        position={[-36.979, 57.975, -56.31]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.137}
      />
      <mesh
        geometry={nodes["icon-instagram"].geometry}
        material={nodes["icon-instagram"].material}
        position={[67.74, 9.568, 54.164]}
        rotation={[Math.PI / 2, 0, 3.076]}
        scale={[7.14, 3.262, 7.14]}
      />
      <mesh
        geometry={nodes["icon-x"].geometry}
        material={nodes["icon-x"].material}
        position={[94.021, 9.568, 50.915]}
        rotation={[Math.PI / 2, 0, 2.96]}
        scale={[7.14, 3.262, 7.14]}
      />
      <mesh
        geometry={nodes["icon-github"].geometry}
        material={nodes["icon-github"].material}
        position={[118.577, 9.568, 46.34]}
        rotation={[Math.PI / 2, 0, 3.126]}
        scale={[7.14, 3.262, 7.14]}
      />
      <mesh
        geometry={nodes["icon-linkedin"].geometry}
        material={nodes["icon-linkedin"].material}
        position={[42.8, 9.568, 59.024]}
        rotation={[Math.PI / 2, 0, 3.049]}
        scale={[7.14, 3.262, 7.14]}
      />
      <mesh
        geometry={nodes["laptop-keybord"].geometry}
        material={nodes["laptop-keybord"].material}
        position={[-21.071, 0, 14.038]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.5}
      />
      <mesh
        geometry={nodes["laptop-bpdy"].geometry}
        material={nodes["laptop-bpdy"].material}
        position={[-20.197, 1.74, 9.611]}
        scale={[15.266, 1.35, 25.976]}
      />
      <mesh
        geometry={nodes["coffee-cup-applied"].geometry}
        material={nodes["coffee-cup-applied"].material}
        position={[5.744, 6.242, 60.542]}
        rotation={[0, -1.361, 0]}
        scale={6.053}
      />
      <mesh
        geometry={nodes["mouse-lift-applied"].geometry}
        material={nodes["mouse-lift-applied"].material}
        position={[2.259, 8.09, -35.65]}
        rotation={[0, 0.807, 0]}
        scale={7.063}
      />
      <mesh
        geometry={nodes["mouse-wheel"].geometry}
        material={nodes["mouse-wheel"].material}
        position={[-0.541, 5.209, -39.295]}
        rotation={[0.215, 0.795, 0.179]}
        scale={[1.308, 0.317, 1.308]}
      />
      <mesh
        geometry={nodes["mouse-pad"].geometry}
        material={nodes["mouse-pad"].material}
        position={[0.67, 0.687, -35.221]}
        scale={13.166}
      />
      <mesh
        geometry={nodes.Headphones.geometry}
        material={nodes.Headphones.material}
        position={[50.048, 10.842, 10.583]}
        rotation={[2.101, 0.237, -2.194]}
        scale={0.767}
      />
      <mesh
        geometry={nodes.notebook.geometry}
        material={nodes.notebook.material}
        position={[133.554, 3.935, 8.931]}
        rotation={[Math.PI, -0.346, Math.PI]}
        scale={9.382}
      />
      <mesh
        geometry={nodes["sketch-paper"].geometry}
        material={nodes["sketch-paper"].material}
        position={[116.33, -0.291, 6.602]}
        scale={3.874}
      />
      <mesh
        geometry={nodes["sketch-paper001"].geometry}
        material={nodes["sketch-paper001"].material}
        position={[125.249, 0.571, -4.907]}
        rotation={[-Math.PI, 0.364, -Math.PI]}
        scale={3.874}
      />
      <mesh
        geometry={nodes["sketch-pen-small"].geometry}
        material={nodes["sketch-pen-small"].material}
        position={[118.271, 3.324, -31.791]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["sketch-pen-big"].geometry}
        material={nodes["sketch-pen-big"].material}
        position={[114.219, 3.343, -28.966]}
        rotation={[Math.PI / 2, 0, 0.283]}
      />
      <mesh
        geometry={nodes["post-box"].geometry}
        material={nodes["post-box"].material}
        position={[116.841, 6.571, 66.816]}
        rotation={[0, 0.743, 0]}
        scale={[8.67, 7.14, 8.67]}
      />
      <mesh
        geometry={nodes["floating-mail"].geometry}
        material={nodes["floating-mail"].material}
        position={[107.089, 18.694, 58.646]}
        rotation={[-0.414, -0.447, -0.086]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail001"].geometry}
        material={nodes["floating-mail001"].material}
        position={[94.054, 24.916, 65.379]}
        rotation={[-0.515, 0.15, -0.069]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail002"].geometry}
        material={nodes["floating-mail002"].material}
        position={[88.756, 31.194, 56.335]}
        rotation={[-0.581, -0.036, 0.179]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail003"].geometry}
        material={nodes["floating-mail003"].material}
        position={[98.211, 21.428, 48.914]}
        rotation={[-0.697, -1.053, -0.451]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail004"].geometry}
        material={nodes["floating-mail004"].material}
        position={[74.899, 24.916, 62.073]}
        rotation={[-0.14, -0.151, 0.095]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail005"].geometry}
        material={nodes["floating-mail005"].material}
        position={[83.567, 21.429, 51.281]}
        rotation={[-0.464, 0.226, -0.183]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail006"].geometry}
        material={nodes["floating-mail006"].material}
        position={[66.267, 37, 66.907]}
        rotation={[-0.687, 0.161, -0.147]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail007"].geometry}
        material={nodes["floating-mail007"].material}
        position={[67.729, 16.954, 53.642]}
        rotation={[-0.069, -0.125, -0.019]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail008"].geometry}
        material={nodes["floating-mail008"].material}
        position={[101.705, 4.716, 45.997]}
        rotation={[-3.107, -1.238, -1.688]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["floating-mail009"].geometry}
        material={nodes["floating-mail009"].material}
        position={[86.801, 0.535, 40.416]}
        rotation={[-0.084, 0.619, 0.039]}
        scale={0.771}
      />
      <mesh
        geometry={nodes["male-head-top001"].geometry}
        material={nodes["male-head-top001"].material}
        position={[163.955, 5.918, 37.279]}
        rotation={[Math.PI, -0.032, Math.PI]}
        scale={3.264}
      />
      <mesh
        geometry={nodes["right-eye001"].geometry}
        material={nodes["right-eye001"].material}
        position={[166.974, 26.509, 28.362]}
        rotation={[Math.PI, -0.032, Math.PI]}
        scale={2.941}
      />
      <mesh
        geometry={nodes["left-eye001"].geometry}
        material={nodes["left-eye001"].material}
        position={[160.273, 26.509, 28.575]}
        rotation={[Math.PI, -0.032, Math.PI]}
        scale={2.941}
      />
      <mesh
        geometry={nodes["male-head-neck001"].geometry}
        material={nodes["male-head-neck001"].material}
        position={[163.955, 5.918, 37.279]}
        rotation={[Math.PI, -0.032, Math.PI]}
        scale={3.264}
      />
      <mesh
        geometry={nodes.skull_low_poly001.geometry}
        material={nodes.skull_low_poly001.material}
        position={[163.949, 29.582, 37.066]}
        rotation={[1.318, 0.008, 3.111]}
        scale={[0.06, 0.058, 0.06]}
      />
      <mesh
        geometry={nodes["male-head-top-inner"].geometry}
        material={nodes["male-head-top-inner"].material}
        position={[163.955, 6.969, 37.279]}
        rotation={[Math.PI, -0.032, Math.PI]}
        scale={3.073}
      />
      <mesh
        geometry={nodes.brain.geometry}
        material={nodes.brain.material}
        position={[163.999, 39.029, 38.659]}
        rotation={[Math.PI / 2, 0, 3.11]}
        scale={[6.592, 7.467, 4.223]}
      />
      <mesh
        geometry={nodes["brain-pin"].geometry}
        material={nodes["brain-pin"].material}
        position={[163.955, 5.918, 37.279]}
        rotation={[Math.PI, -0.032, Math.PI]}
        scale={3.264}
      />
      <mesh
        geometry={nodes["podium-head-statue"].geometry}
        material={nodes["podium-head-statue"].material}
        position={[163.474, 8.479, 38.701]}
        scale={12.63}
      />
      <mesh
        geometry={nodes["glasses-closed"].geometry}
        material={nodes["glasses-closed"].material}
        position={[157.985, 8.673, 31.283]}
        rotation={[1.32, 0.157, -0.383]}
        scale={[8.651, 8.122, 8.122]}
      />
      <mesh
        geometry={nodes["atelier-ground"].geometry}
        material={nodes["atelier-ground"].material}
        position={[0, -5, 0]}
      />
      <mesh
        geometry={nodes["atelier-walls"].geometry}
        material={nodes["atelier-walls"].material}
        position={[0, 0.156, 0]}
      />
      <mesh
        geometry={nodes["tatami-blocks"].geometry}
        material={nodes["tatami-blocks"].material}
        position={[74.87, -1, 4.648]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.26}
      />
      <mesh
        geometry={nodes["wood-prank004"].geometry}
        material={nodes["wood-prank004"].material}
        position={[-418.079, 0.493, -76.402]}
        scale={[1.6, 1, 1]}
      />
      <mesh
        geometry={nodes["wood-prank005"].geometry}
        material={nodes["wood-prank005"].material}
        position={[193.955, 0.493, -384.544]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.6, 1, 1]}
      />
      <mesh
        geometry={nodes.roof.geometry}
        material={nodes.roof.material}
        position={[65.324, 103.178, 24.991]}
        scale={53.256}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[233.735, 59.671, 72.194]}
        scale={[3.898, 67.047, 3.898]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[233.735, 59.671, -115.391]}
        scale={[3.898, 67.047, 3.898]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[78.608, 59.671, -115.391]}
        scale={[3.898, 67.047, 3.898]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-29.504, 59.671, -115.391]}
        scale={[3.898, 67.047, 3.898]}
      />
      <mesh
        geometry={nodes["tatami-blocks001"].geometry}
        material={nodes["tatami-blocks001"].material}
        position={[90.514, -1, -483.238]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.26}
      />
      <mesh
        geometry={nodes["wood-prank006"].geometry}
        material={nodes["wood-prank006"].material}
        position={[9.883, 0.493, 253.874]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.6, 1, 1]}
      />
      <mesh
        geometry={nodes["wood-prank007"].geometry}
        material={nodes["wood-prank007"].material}
        position={[-298.259, 0.493, -358.16]}
        scale={[1.6, 1, 1]}
      />
      <mesh
        geometry={nodes["hallway-frame"].geometry}
        material={nodes["hallway-frame"].material}
        position={[-11.121, 27.207, -163.585]}
        rotation={[0, 0, -Math.PI]}
        scale={[-40.128, -49.172, -3.594]}
      />
      <mesh
        geometry={nodes.roof001.geometry}
        material={nodes.roof001.material}
        position={[61.513, 88.984, -448.081]}
        scale={30.682}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[158.16, 59.671, -359.018]}
        scale={[3.898, 67.047, 3.898]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-29.504, 59.671, -359.018]}
        scale={[3.898, 67.047, 3.898]}
      />
      <mesh
        geometry={nodes.glassBrick01007.geometry}
        material={nodes.glassBrick01007.material}
        position={[-133.336, 38.126, -268.766]}
        rotation={[-3.03, -0.19, 1.731]}
        scale={8.516}
      />
      <mesh
        geometry={nodes.glassBrick02007.geometry}
        material={nodes.glassBrick02007.material}
        position={[-151.081, 22.912, -282.043]}
        rotation={[3.009, -0.29, 2.554]}
        scale={8.516}
      />
      <mesh
        geometry={nodes["led-light-socket004"].geometry}
        material={nodes["led-light-socket004"].material}
        position={[-136.572, 56.82, -271.889]}
        rotation={[0.027, -0.727, -0.251]}
        scale={[50.274, 2.279, 50.274]}
      />
      <mesh
        geometry={nodes["led-light-wire-curve011"].geometry}
        material={nodes["led-light-wire-curve011"].material}
        position={[-146.555, 62.101, -268.254]}
        rotation={[1.478, 0.133, 2.849]}
        scale={10.133}
      />
      <mesh
        geometry={nodes["wood-frame-bottom004"].geometry}
        material={nodes["wood-frame-bottom004"].material}
        position={[-144.09, 8.299, -273.813]}
        rotation={[0.321, -1.25, 0.433]}
        scale={[5.32, 0.76, 6.1]}
      />
      <mesh
        geometry={nodes["wood-frame-left004"].geometry}
        material={nodes["wood-frame-left004"].material}
        position={[-124.403, 30.181, -288.351]}
        rotation={[2.895, 0.995, -3.085]}
        scale={[5.32, 16.973, 0.76]}
      />
      <mesh
        geometry={nodes["wood-frame-right004"].geometry}
        material={nodes["wood-frame-right004"].material}
        position={[-165.321, 34.205, -264.415]}
        rotation={[0.418, -0.83, 0.562]}
        scale={[5.32, 16.973, 0.76]}
      />
      <mesh
        geometry={nodes["wood-frame-top004"].geometry}
        material={nodes["wood-frame-top004"].material}
        position={[-146.723, 63.204, -265.211]}
        rotation={[-2.237, 1.04, -0.479]}
        scale={[5.32, 0.76, 6.1]}
      />
      <mesh
        geometry={nodes["wood-stick-back004"].geometry}
        material={nodes["wood-stick-back004"].material}
        position={[-145.004, 17.977, -268.258]}
        rotation={[1.532, 0.303, 1.401]}
        scale={[10.133, 6.84, 10.133]}
      />
      <mesh
        geometry={nodes["wood-stick-front004"].geometry}
        material={nodes["wood-stick-front004"].material}
        position={[-153.226, 38.189, -279.075]}
        rotation={[0.597, -0.039, 0.563]}
        scale={[10.133, 6.84, 10.133]}
      />
      <mesh
        geometry={nodes["float-particles007"].geometry}
        material={nodes["float-particles007"].material}
        position={[-247.184, 13.085, -500.734]}
        rotation={[Math.PI / 2, 0, -0.219]}
        scale={[22.903, 17.377, 16.426]}
      />
      <mesh
        geometry={nodes["tree-leaves-low-poly010"].geometry}
        material={nodes["tree-leaves-low-poly010"].material}
        position={[-284.716, 14.363, -443.148]}
        rotation={[0.662, -0.78, -1.45]}
        scale={1.382}
      />
      <mesh
        geometry={nodes["tree-leaves-low-poly011"].geometry}
        material={nodes["tree-leaves-low-poly011"].material}
        position={[-315.248, 9.415, -473.631]}
        rotation={[1.01, -0.432, 1.894]}
        scale={2.765}
      />
      <mesh
        geometry={nodes["tree-trunks-low-poly001"].geometry}
        material={nodes["tree-trunks-low-poly001"].material}
        position={[-283.982, 14.82, -443.735]}
        rotation={[0.662, -0.78, -1.45]}
        scale={1.382}
      />
      <mesh
        geometry={nodes["circle-window-frame001"].geometry}
        material={nodes["circle-window-frame001"].material}
        position={[-193.99, 28.703, -498.313]}
        rotation={[Math.PI / 2, 0, -1.575]}
        scale={[1.582, 1.034, 1.582]}
      />
      <mesh
        geometry={nodes["scenery-window-mask001"].geometry}
        material={nodes["scenery-window-mask001"].material}
        position={[-197.998, 28.988, -498.384]}
        rotation={[Math.PI / 2, 0, -1.575]}
        scale={7.427}
      />
      <mesh
        geometry={nodes["digital-world001"].geometry}
        material={nodes["digital-world001"].material}
        position={[-267.741, 29.465, -497.886]}
        rotation={[-Math.PI, 1.567, -Math.PI]}
      />
      <mesh
        geometry={nodes["scenery-reflection-on-the-ground002"].geometry}
        material={nodes["scenery-reflection-on-the-ground002"].material}
        position={[-159.81, 5.485, -497.704]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes["weather-models001"].geometry}
        material={nodes["weather-models001"].material}
        position={[-220.181, 33.601, -511.606]}
        rotation={[Math.PI / 2, 0, -0.955]}
        scale={0.063}
      />
      <mesh
        geometry={nodes.clouds002.geometry}
        material={nodes.clouds002.material}
        position={[-220.181, 33.601, -511.606]}
        rotation={[Math.PI / 2, 0, -0.955]}
        scale={0.063}
      />
      <mesh
        geometry={nodes["rain-drop010"].geometry}
        material={nodes["rain-drop010"].material}
        position={[-212.267, 47.048, -513.71]}
        rotation={[0, 0.955, 0]}
        scale={[1.31, 1.975, 1.31]}
      />
      <mesh
        geometry={nodes["rain-drop011"].geometry}
        material={nodes["rain-drop011"].material}
        position={[-216.521, 41.009, -518.798]}
        rotation={[0, 0.955, 0]}
        scale={[1.751, 2.641, 1.751]}
      />
      <mesh
        geometry={nodes["rain-drop012"].geometry}
        material={nodes["rain-drop012"].material}
        position={[-211.574, 34.552, -517.954]}
        rotation={[0, 0.955, 0]}
        scale={[1.257, 1.896, 1.257]}
      />
      <mesh
        geometry={nodes["rain-drop013"].geometry}
        material={nodes["rain-drop013"].material}
        position={[-212.443, 27.027, -523.419]}
        rotation={[0, 0.955, 0]}
        scale={[1.31, 1.975, 1.31]}
      />
      <mesh
        geometry={nodes["rain-drop014"].geometry}
        material={nodes["rain-drop014"].material}
        position={[-216.774, 49.277, -523.827]}
        rotation={[0, 0.955, 0]}
        scale={[1.105, 1.667, 1.105]}
      />
      <mesh
        geometry={nodes["base-wood006"].geometry}
        material={nodes["base-wood006"].material}
        position={[204.558, 6.996, -266.026]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["connection-wood005"].geometry}
        material={nodes["connection-wood005"].material}
        position={[204.558, 6.996, -266.026]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      />
      <mesh
        geometry={nodes.Cube056.geometry}
        material={nodes.Cube056.material}
        position={[165.313, 33.342, -246.403]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[0.89, 11.914, 1.854]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={nodes.Cube057.material}
        position={[157.414, 19.579, -248.118]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[1.252, 1.777, 9.317]}
      />
      <mesh
        geometry={nodes["marble-a006"].geometry}
        material={nodes["marble-a006"].material}
        position={[204.558, 6.996, -266.026]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["marble-b-1005"].geometry}
        material={nodes["marble-b-1005"].material}
        position={[202.989, 25.195, -257.513]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["marble-b-2005"].geometry}
        material={nodes["marble-b-2005"].material}
        position={[202.811, 27.005, -257.695]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["marble-b-3005"].geometry}
        material={nodes["marble-b-3005"].material}
        position={[202.811, 27.005, -257.695]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["marble-c-1002"].geometry}
        material={nodes["marble-c-1002"].material}
        position={[204.903, 36.389, -229.353]}
        rotation={[1.802, 0.371, -0.347]}
        scale={[-12.22, -1.201, -12.22]}
      />
      <mesh
        geometry={nodes["marble-c-2002"].geometry}
        material={nodes["marble-c-2002"].material}
        position={[197.356, 56.173, -234.872]}
        rotation={[2.147, -0.312, 1.583]}
        scale={[-12.22, -1.201, -12.22]}
      />
      <mesh
        geometry={nodes["marble-d-1002"].geometry}
        material={nodes["marble-d-1002"].material}
        position={[216.873, 59.291, -294.616]}
        rotation={[0.421, 1.04, 1.018]}
        scale={[1.105, 0.989, 1.105]}
      />
      <mesh
        geometry={nodes["marble-d-2002"].geometry}
        material={nodes["marble-d-2002"].material}
        position={[221.818, 46.256, -299.982]}
        rotation={[-0.201, -0.446, -1.87]}
        scale={[1.105, 0.989, 1.105]}
      />
      <mesh
        geometry={nodes["marble-d-3002"].geometry}
        material={nodes["marble-d-3002"].material}
        position={[211.39, 39.084, -293.18]}
        rotation={[0.421, 1.04, 1.018]}
        scale={[1.105, 0.989, 1.105]}
      />
      <mesh
        geometry={nodes["marble-d-4002"].geometry}
        material={nodes["marble-d-4002"].material}
        position={[224.228, 46.657, -304.325]}
        rotation={[-0.201, -0.446, 2.842]}
        scale={2.665}
      />
      <mesh
        geometry={nodes.stone002.geometry}
        material={nodes.stone002.material}
        position={[286.753, 15.625, -307.039]}
        rotation={[Math.PI / 2, 0, -3.044]}
        scale={15.467}
      />
      <mesh
        geometry={nodes["stone-support-wood-01002"].geometry}
        material={nodes["stone-support-wood-01002"].material}
        position={[287.603, 8.602, -307.772]}
        rotation={[-Math.PI, 0.097, -Math.PI]}
        scale={[1.6, 1.6, 16.174]}
      />
      <mesh
        geometry={nodes["stone-support-wood-02002"].geometry}
        material={nodes["stone-support-wood-02002"].material}
        position={[287.603, 8.602, -307.772]}
        rotation={[Math.PI, -1.473, Math.PI]}
        scale={[1.6, 1.6, 16.174]}
      />
      <mesh
        geometry={nodes["stone-wood-column002"].geometry}
        material={nodes["stone-wood-column002"].material}
        position={[287.603, 51.509, -307.772]}
        rotation={[-Math.PI, 0.097, -Math.PI]}
        scale={[4.891, 24.408, 4.891]}
      />
      <mesh
        geometry={nodes["wood-cylinder-inside-marble-01002"].geometry}
        material={nodes["wood-cylinder-inside-marble-01002"].material}
        position={[206.619, 36.554, -223.196]}
        rotation={[-1.339, -0.371, -2.795]}
        scale={[1.913, 1.17, 1.913]}
      />
      <mesh
        geometry={nodes["wood-cylinder-inside-marble-02002"].geometry}
        material={nodes["wood-cylinder-inside-marble-02002"].material}
        position={[190.434, 58.602, -230.216]}
        rotation={[-0.995, 0.312, 1.559]}
        scale={[1.913, 1.17, 1.913]}
      />
      <mesh
        geometry={nodes["wood-locking-01002"].geometry}
        material={nodes["wood-locking-01002"].material}
        position={[220.865, 58.447, -296.599]}
        rotation={[-0.201, -0.446, 1.271]}
        scale={[2.993, 6.188, 1.274]}
      />
      <mesh
        geometry={nodes["wood-locking-02002"].geometry}
        material={nodes["wood-locking-02002"].material}
        position={[217.33, 47.933, -299.182]}
        rotation={[0.421, 1.04, -2.124]}
        scale={[2.993, 6.188, 1.274]}
      />
      <mesh
        geometry={nodes["wood-locking-03002"].geometry}
        material={nodes["wood-locking-03002"].material}
        position={[215.249, 38.152, -295.21]}
        rotation={[-0.201, -0.446, 1.271]}
        scale={[2.993, 6.188, 1.274]}
      />
      <mesh
        geometry={nodes["wood-stand005"].geometry}
        material={nodes["wood-stand005"].material}
        position={[204.558, 6.996, -266.026]}
        rotation={[0.134, -0.786, 0.201]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["wood-stand-04002"].geometry}
        material={nodes["wood-stand-04002"].material}
        position={[163.303, 30.679, -253.114]}
        rotation={[0.305, 0.23, 1.422]}
        scale={[6.941, 11.215, 1.996]}
      />
      <mesh
        geometry={nodes["wood-stand-b005"].geometry}
        material={nodes["wood-stand-b005"].material}
        position={[202.811, 27.005, -257.695]}
        rotation={[2.914, -1.225, 3.004]}
        scale={2.089}
      />
      <mesh
        geometry={nodes["typo-A-backwall002"].geometry}
        material={nodes["typo-A-backwall002"].material}
        position={[483.068, 8.775, -113.622]}
        rotation={[Math.PI, -0.731, Math.PI]}
        scale={[57.602, 97.036, 1.286]}
      />
      <mesh
        geometry={nodes["typo-A-line-horizontal002"].geometry}
        material={nodes["typo-A-line-horizontal002"].material}
        position={[478.711, 56.08, -117.757]}
        rotation={[Math.PI, -0.731, Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-A-big-circle002"].geometry}
        material={nodes["typo-A-big-circle002"].material}
        position={[474.159, 56.08, -122.832]}
        rotation={[Math.PI, -0.731, Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-A-line-vertical-left002"].geometry}
        material={nodes["typo-A-line-vertical-left002"].material}
        position={[487.71, 56.08, -143.937]}
        rotation={[Math.PI, -0.731, Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-A-line-vertical-right002"].geometry}
        material={nodes["typo-A-line-vertical-right002"].material}
        position={[451.694, 56.08, -111.635]}
        rotation={[Math.PI, -0.731, Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-B-backwall002"].geometry}
        material={nodes["typo-B-backwall002"].material}
        position={[507.126, 8.775, -29.62]}
        rotation={[0, -0.219, 0]}
        scale={[57.602, 97.036, 1.286]}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-bottom002"].geometry}
        material={nodes["typo-B-line-horizontal-bottom002"].material}
        position={[504.786, 30.329, -17.542]}
        rotation={[0, -0.219, 0]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-top003"].geometry}
        material={nodes["typo-B-line-horizontal-top003"].material}
        position={[504.454, 80.783, -16.125]}
        rotation={[0, -0.219, 0]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-B-line-horizontal-middle002"].geometry}
        material={nodes["typo-B-line-horizontal-middle002"].material}
        position={[504.786, 55.541, -17.542]}
        rotation={[0, -0.219, 0]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-B-line-vertical002"].geometry}
        material={nodes["typo-B-line-vertical002"].material}
        position={[479.412, 56.08, -15.252]}
        rotation={[0, -0.219, 0]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-B-small-circle-top002"].geometry}
        material={nodes["typo-B-small-circle-top002"].material}
        position={[518.062, 68.24, -20.84]}
        rotation={[0, -0.219, 0]}
        scale={25.413}
      />
      <mesh
        geometry={nodes["typo-B-small-circle-bottom002"].geometry}
        material={nodes["typo-B-small-circle-bottom002"].material}
        position={[518.062, 42.827, -20.84]}
        rotation={[0, -0.219, 0]}
        scale={25.413}
      />
      <mesh
        geometry={nodes["typo-C-backwall002"].geometry}
        material={nodes["typo-C-backwall002"].material}
        position={[566.994, 8.775, -89.626]}
        rotation={[-Math.PI, 1.245, -Math.PI]}
        scale={[57.602, 97.036, 1.286]}
      />
      <mesh
        geometry={nodes["typo-C-big-circle002"].geometry}
        material={nodes["typo-C-big-circle002"].material}
        position={[572.912, 56.082, -92.153]}
        rotation={[-Math.PI, 1.245, -Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-C-line-horizontal-bottom002"].geometry}
        material={nodes["typo-C-line-horizontal-bottom002"].material}
        position={[579.8, 31.902, -94.49]}
        rotation={[-Math.PI, 1.245, -Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-C-line-horizontal-top002"].geometry}
        material={nodes["typo-C-line-horizontal-top002"].material}
        position={[579.8, 80.283, -94.49]}
        rotation={[-Math.PI, 1.245, -Math.PI]}
        scale={24.341}
      />
      <mesh
        geometry={nodes["typo-graphic-wood-stick-bottom002"].geometry}
        material={nodes["typo-graphic-wood-stick-bottom002"].material}
        position={[522.955, 14.515, -246.804]}
        rotation={[3.142, 1.553, 1.571]}
        scale={[-0.745, -29.292, -0.745]}
      />
      <mesh
        geometry={nodes["typo-graphic-textile002"].geometry}
        material={nodes["typo-graphic-textile002"].material}
        position={[522.956, 56.877, -246.715]}
        rotation={[0, -1.553, 1.571]}
        scale={1.488}
      />
      <mesh
        geometry={nodes["typo-graphic-wood-stick-top002"].geometry}
        material={nodes["typo-graphic-wood-stick-top002"].material}
        position={[522.955, 99.239, -246.804]}
        rotation={[3.142, 1.553, 1.571]}
        scale={[-0.745, -29.292, -0.745]}
      />
      <mesh
        geometry={nodes["typo-alphabet-a"].geometry}
        material={nodes["typo-alphabet-a"].material}
        position={[398.319, 2.956, -219.292]}
        rotation={[Math.PI / 2, 0, 1.359]}
        scale={315.279}
      />
      <mesh
        geometry={nodes["typo-alphabet-b"].geometry}
        material={nodes["typo-alphabet-b"].material}
        position={[405.832, 2.956, -184.309]}
        rotation={[Math.PI / 2, 0, 1.359]}
        scale={315.279}
      />
      <mesh
        geometry={nodes["typo-alphabet-c"].geometry}
        material={nodes["typo-alphabet-c"].material}
        position={[413.051, 2.956, -150.697]}
        rotation={[Math.PI / 2, 0, 1.359]}
        scale={315.279}
      />
      <mesh
        geometry={nodes["typo-hiragana-a"].geometry}
        material={nodes["typo-hiragana-a"].material}
        position={[449.872, 23.146, -241.934]}
        rotation={[Math.PI / 2, 0, 1.359]}
        scale={315.279}
      />
      <mesh
        geometry={nodes["typo-hiragana-i"].geometry}
        material={nodes["typo-hiragana-i"].material}
        position={[457.385, 23.146, -206.951]}
        rotation={[Math.PI / 2, 0, 1.359]}
        scale={315.279}
      />
      <mesh
        geometry={nodes["typo-hiragana-u"].geometry}
        material={nodes["typo-hiragana-u"].material}
        position={[464.604, 23.146, -173.339]}
        rotation={[Math.PI / 2, 0, 1.359]}
        scale={315.279}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={nodes.Cube037.material}
        position={[398.306, 3.168, -219.352]}
        rotation={[0, -1.359, 0]}
        scale={[13.378, 13.378, 4.704]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={nodes.Cube038.material}
        position={[405.805, 3.168, -184.436]}
        rotation={[0, -1.359, 0]}
        scale={[13.378, 13.378, 4.704]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={nodes.Cube039.material}
        position={[412.952, 3.168, -151.157]}
        rotation={[0, -1.359, 0]}
        scale={[13.378, 13.378, 4.704]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={nodes.Cube040.material}
        position={[449.605, 23.13, -243.179]}
        rotation={[0, -1.359, 0]}
        scale={13.378}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        position={[457.103, 23.13, -208.263]}
        rotation={[0, -1.359, 0]}
        scale={13.378}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={nodes.Cube042.material}
        position={[464.25, 23.13, -174.984]}
        rotation={[0, -1.359, 0]}
        scale={13.378}
      />
      <mesh
        geometry={nodes["mesh-comforting-dinner-cutlery001"].geometry}
        material={nodes["mesh-comforting-dinner-cutlery001"].material}
        position={[574.382, 40.635, -575.538]}
        rotation={[2.715, -1.395, 2.236]}
        scale={12.497}
      />
      <mesh
        geometry={nodes["mesh-comforting-dinner-humans001"].geometry}
        material={nodes["mesh-comforting-dinner-humans001"].material}
        position={[249.839, -55.112, -878.149]}
        rotation={[Math.PI / 2, 0, 0.731]}
        scale={198.515}
      />
      <mesh
        geometry={nodes["mesh-donuts-universe001"].geometry}
        material={nodes["mesh-donuts-universe001"].material}
        position={[177.35, 22.416, 147.464]}
        rotation={[1.564, -0.209, 1.757]}
        scale={336.887}
      />
      <mesh
        geometry={nodes["mesh-marble-race001"].geometry}
        material={nodes["mesh-marble-race001"].material}
        position={[184.117, 0.049, 242.512]}
        rotation={[2.604, -1.304, 2.535]}
        scale={7.72}
      />
      <mesh
        geometry={nodes["mesh-object-rotterdam-2024001"].geometry}
        material={nodes["mesh-object-rotterdam-2024001"].material}
        position={[68.792, -1.853, 246.752]}
        rotation={[2.623, -1.052, 2.728]}
        scale={0.589}
      />
      <mesh
        geometry={nodes["mesh-weather-cereal001"].geometry}
        material={nodes["mesh-weather-cereal001"].material}
        position={[47.778, 17.707, 143.283]}
        rotation={[-1.645, -0.429, -1.312]}
        scale={0.97}
      />
      <mesh
        geometry={nodes["box-cutter001"].geometry}
        material={nodes["box-cutter001"].material}
        position={[244.225, 33.683, 138.385]}
        rotation={[0.587, -0.66, 0.899]}
        scale={[7.888, 5.92, 5.92]}
      />
      <mesh
        geometry={nodes["foam-board-01001"].geometry}
        material={nodes["foam-board-01001"].material}
        position={[290.724, -1.835, 169.94]}
        rotation={[0, 0, -0.084]}
        scale={[0.99, 1.03, 1.03]}
      />
      <mesh
        geometry={nodes["foam-board-02001"].geometry}
        material={nodes["foam-board-02001"].material}
        position={[286.243, -2.003, 178.257]}
        rotation={[0, 0, -0.084]}
        scale={[0.99, 1.03, 1.03]}
      />
      <mesh
        geometry={nodes["foam-board-03001"].geometry}
        material={nodes["foam-board-03001"].material}
        position={[281.004, -1.835, 169.94]}
        rotation={[0, 0, -0.084]}
        scale={[0.869, 0.905, 0.905]}
      />
      <mesh
        geometry={nodes.ruler001.geometry}
        material={nodes.ruler001.material}
        position={[136.602, -26.862, 208.997]}
        rotation={[-0.004, -0.08, 0.367]}
        scale={5.462}
      />
      <mesh
        geometry={nodes["pencil-body-01001"].geometry}
        material={nodes["pencil-body-01001"].material}
        position={[115.132, 6.352, 122.46]}
        rotation={[1.887, 1.102, -2.459]}
        scale={2.325}
      />
      <mesh
        geometry={nodes["pencil-body-02001"].geometry}
        material={nodes["pencil-body-02001"].material}
        position={[115.091, 6.239, 122.541]}
        rotation={[1.887, 1.102, -2.459]}
        scale={2.325}
      />
      <mesh
        geometry={nodes["cutting-mat001"].geometry}
        material={nodes["cutting-mat001"].material}
        position={[202.329, 73.729, 238.559]}
        rotation={[0.02, -0.297, 0.185]}
        scale={[104.433, 18.09, 78.325]}
      />
      <mesh
        geometry={nodes["analog-tv-shells001"].geometry}
        material={nodes["analog-tv-shells001"].material}
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={nodes["analog-tv-01-modified-square-screen002"].geometry}
        material={nodes["analog-tv-01-modified-square-screen002"].material}
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={
          nodes["analog-tv-02-modified-horizontal-screen-01002"].geometry
        }
        material={
          nodes["analog-tv-02-modified-horizontal-screen-01002"].material
        }
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={
          nodes["analog-tv-02-modified-horizontal-screen-02002"].geometry
        }
        material={
          nodes["analog-tv-02-modified-horizontal-screen-02002"].material
        }
        position={[-240.884, -15.754, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={nodes["analog-tv-03-modified-horizontal-screen002"].geometry}
        material={nodes["analog-tv-03-modified-horizontal-screen002"].material}
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={
          nodes["analog-tv-03-modified-vertical-big-screen002"].geometry
        }
        material={
          nodes["analog-tv-03-modified-vertical-big-screen002"].material
        }
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={
          nodes["analog-tv-03-modified-vertical-small-screen002"].geometry
        }
        material={
          nodes["analog-tv-03-modified-vertical-small-screen002"].material
        }
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={nodes["analog-tv-04-modified-horizontal-screen002"].geometry}
        material={nodes["analog-tv-04-modified-horizontal-screen002"].material}
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={nodes["analog-tv-05-modified-horizontal-screen002"].geometry}
        material={nodes["analog-tv-05-modified-horizontal-screen002"].material}
        position={[-240.884, -13.857, -45.239]}
        rotation={[-Math.PI, 0.731, -Math.PI]}
        scale={1.68}
      />
      <mesh
        geometry={nodes["photo-screen002"].geometry}
        material={nodes["photo-screen002"].material}
        position={[-171.018, 14.1, 158.56]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[1.626, 2.297, 1.626]}
      />
      <mesh
        geometry={nodes["spotlight-01002"].geometry}
        material={nodes["spotlight-01002"].material}
        position={[-89.625, -5.863, 113.734]}
        rotation={[1.567, 0, 0.478]}
        scale={0.465}
      />
      <mesh
        geometry={nodes["spotlight-02002"].geometry}
        material={nodes["spotlight-02002"].material}
        position={[-150.436, -5.863, 214.335]}
        rotation={[1.575, -0.001, -3.076]}
        scale={0.465}
      />
      <mesh
        geometry={nodes["camera-low-poly002"].geometry}
        material={nodes["camera-low-poly002"].material}
        position={[-53.961, 18.877, 152.448]}
        rotation={[Math.PI / 2, 0, -1.574]}
        scale={[4.456, 1.485, 4.456]}
      />
      <mesh
        geometry={nodes["camera-low-poly-screen001"].geometry}
        material={nodes["camera-low-poly-screen001"].material}
        position={[-53.961, 18.877, 152.448]}
        rotation={[Math.PI / 2, 0, -1.574]}
        scale={[4.456, 1.485, 4.456]}
      />
      <mesh
        geometry={nodes["mesh-blooming-flower001"].geometry}
        material={nodes["mesh-blooming-flower001"].material}
        position={[-137.178, 12.071, 163.62]}
        rotation={[Math.PI / 2, 0, 0.484]}
        scale={1.948}
      />
      <mesh
        geometry={nodes["sculpture-stand-square-small002"].geometry}
        material={nodes["sculpture-stand-square-small002"].material}
        position={[-135.057, -12.267, 161.319]}
        scale={1.948}
      />
      <mesh
        geometry={nodes["clay-board002"].geometry}
        material={nodes["clay-board002"].material}
        position={[-106.727, 9.001, 45.406]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["clay-in-process-01002"].geometry}
        material={nodes["clay-in-process-01002"].material}
        position={[-94.935, 9.989, 9.227]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["clay-in-process-02002"].geometry}
        material={nodes["clay-in-process-02002"].material}
        position={[-92.277, 11.874, 17.42]}
        rotation={[-0.482, -0.017, 0.033]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["mesh-equence-river-soil001"].geometry}
        material={nodes["mesh-equence-river-soil001"].material}
        position={[-171.134, 8.397, 14.181]}
        rotation={[0, 0.29, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["mesh-glass-popping001"].geometry}
        material={nodes["mesh-glass-popping001"].material}
        position={[-158.251, 21.11, 75.175]}
        rotation={[0, 0.34, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["mesh-silky-sphere001"].geometry}
        material={nodes["mesh-silky-sphere001"].material}
        position={[-129.928, 27.246, 64.486]}
        rotation={[0, 0.191, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes.paper002.geometry}
        material={nodes.paper002.material}
        position={[-106.701, 8.167, 74.422]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["sculpture-stand-round002"].geometry}
        material={nodes["sculpture-stand-round002"].material}
        position={[-129.242, -8.564, 64.577]}
        rotation={[0, 0.191, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["sculpture-stand-square-big002"].geometry}
        material={nodes["sculpture-stand-square-big002"].material}
        position={[-160.701, -8.564, 74.997]}
        rotation={[0, -0.091, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["sculpture-tool-01002"].geometry}
        material={nodes["sculpture-tool-01002"].material}
        position={[-94.368, 8.534, -8.909]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["sculpture-tool-02002"].geometry}
        material={nodes["sculpture-tool-02002"].material}
        position={[-95.368, 8.493, -3.725]}
        rotation={[0, -1.571, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["working-desk-workshop006"].geometry}
        material={nodes["working-desk-workshop006"].material}
        position={[-183.058, -8.564, 17.321]}
        rotation={[0, 0.29, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["working-desk-workshop007"].geometry}
        material={nodes["working-desk-workshop007"].material}
        position={[-158.638, -8.564, 10.031]}
        rotation={[0, 0.29, 0]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["working-desk-workshop008"].geometry}
        material={nodes["working-desk-workshop008"].material}
        position={[-93.669, -8.564, 17.88]}
        scale={1.604}
      />
      <mesh
        geometry={nodes["virtual-grid"].geometry}
        material={nodes["virtual-grid"].material}
        position={[-68.903, -5.294, 178.675]}
        scale={-150.588}
      />
      <mesh
        geometry={nodes["virtual-grid-space"].geometry}
        material={nodes["virtual-grid-space"].material}
        position={[-148.464, 0, 225.17]}
        scale={-111.983}
      />
      <mesh
        geometry={nodes["hands-low-poly001"].geometry}
        material={nodes["hands-low-poly001"].material}
        position={[-10.245, 12.411, 34.537]}
        rotation={[-2.258, -1.194, -2.383]}
        scale={28.865}
      />
    </group>
  );
}

useGLTF.preload("/models/new-atelier/new-atelier-mono.glb");
