/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/glass-lens-objects/glass-lens-objects.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function GlassLensObjects({ material, objectIndex, ...props }) {
  const { nodes } = useGLTF(
    "./models/glass-lens-objects/glass-lens-objects.glb"
  );

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.icoSphere.geometry} visible={objectIndex === 1}>
        {material}
      </mesh>
      <mesh geometry={nodes.uvSphere.geometry} visible={objectIndex === 2}>
        {material}
      </mesh>
      <mesh
        geometry={nodes.virticalStripesBig.geometry}
        visible={objectIndex === 3}
      >
        {material}
      </mesh>
      <mesh geometry={nodes.hexagon.geometry} visible={objectIndex === 4}>
        {material}
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/glass-lens-objects/glass-lens-objects.glb");
