/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/monolith/monolith.glb 
*/

import React from "react";
import { useGLTF, Clone } from "@react-three/drei";

export default function Monolith(props) {
  const { nodes } = useGLTF("./models/monolith/monolith.glb");
  return (
    <group {...props} dispose={null}>
      <Clone
        object={nodes["monolith-body"]}
        inject={
          <meshStandardMaterial
            color="#91989F"
            metalness={0.75}
            roughness={0.2}
          />
        }
      />
    </group>
  );
}

useGLTF.preload("./models/monolith/monolith.glb");
