/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/tile-ground/tile-ground.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function TileGround(props) {
  const { nodes, materials } = useGLTF("./models/tile-ground/tile-ground.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["tile-ground"].geometry}
        material={materials["tile-ground-material"]}
      />
    </group>
  );
}

useGLTF.preload("./models/tile-ground/tile-ground.glb");
