/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/male-head/male-head.glb 
*/

import React, { useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const HEAD_MOVE_STRENGTH = 0.04;
const EYE_BALLS_MOVE_STRENGTH = 0.05;

export default function MaleHead(props) {
  /**
   * LOAD THE MODEL
   */
  const { nodes, materials } = useGLTF("./models/male-head/male-head.glb");

  /**
   * REF - UPPER HEAD, EYE BALLS
   */
  const upperHeadPart = useRef();
  const eyeBallRight = useRef();
  const eyeBallLeft = useRef();

  /**
   * MOUSE POINTER MOVE SETTING
   */
  const mouse = new THREE.Vector2();

  useEffect(() => {
    window.addEventListener("pointermove", (event) => {
      if (event.isPrimary === false) return;

      // Scale half window side into 1% for mouse movements
      mouse.x = (event.clientX - window.innerWidth / 2) * 0.02;
      mouse.y = (event.clientY - window.innerHeight / 2) * 0.02;
    });
  }, []);

  useFrame((state, delta) => {
    upperHeadPart.current.rotation.y = mouse.x * HEAD_MOVE_STRENGTH;
    upperHeadPart.current.rotation.x = mouse.y * HEAD_MOVE_STRENGTH;

    eyeBallRight.current.rotation.y = mouse.x * EYE_BALLS_MOVE_STRENGTH;
    eyeBallRight.current.rotation.x = mouse.y * EYE_BALLS_MOVE_STRENGTH;

    eyeBallLeft.current.rotation.y = mouse.x * EYE_BALLS_MOVE_STRENGTH;
    eyeBallLeft.current.rotation.x = mouse.y * EYE_BALLS_MOVE_STRENGTH;
  });

  return (
    <group {...props} dispose={null}>
      {/* ---- MOVE WITH POINTER ---- */}

      <group ref={upperHeadPart} rotation={[0, 0, 0]}>
        {/* MALE HEAD TOP */}
        <mesh
          geometry={nodes["male-head-top"].geometry}
          // material={materials["head-skin"]}
        >
          <meshStandardMaterial
            color="#91989F"
            metalness={0.8}
            roughness={0.01}
          />
        </mesh>

        {/* GLASSES */}
        <mesh
          geometry={nodes["glassese-front-frame"].geometry}
          material={materials["glasses-black"]}
        />
        <mesh
          geometry={nodes["glasses-hinge"].geometry}
          material={materials["SVGMat-gold"]}
        />
        <mesh
          geometry={nodes["glassese-side-frame"].geometry}
          material={materials["glasses-black"]}
        />

        {/* EYES */}
        <mesh
          ref={eyeBallRight}
          geometry={nodes["right-eye"].geometry}
          material={materials["eye-ball-material"]}
          position={[-1.115, 6.309, 2.809]}
        />
        <mesh
          ref={eyeBallLeft}
          geometry={nodes["left-eye"].geometry}
          material={materials["eye-ball-material"]}
          position={[1.115, 6.309, 2.809]}
        />
      </group>

      {/* ---- FIXED ---- */}

      {/* MALE HEAD NECK */}
      <mesh
        geometry={nodes["male-head-neck"].geometry}
        // material={materials["head-skin"]}
      >
        <meshStandardMaterial
          color="#91989F"
          metalness={0.8}
          roughness={0.01}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/male-head/male-head.glb");
