/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/male-head/male-head.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function MaleHead(props) {
  const { nodes, materials } = useGLTF("./models/male-head/male-head.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["male-head-top"].geometry}
        material={materials.SVGMat}
      />
      <mesh
        geometry={nodes["glassese-front-frame"].geometry}
        material={materials["eye-ball-black"]}
      />
      <mesh
        geometry={nodes["glasses-hinge"].geometry}
        material={materials["SVGMat-gold"]}
      />
      <mesh
        geometry={nodes["glassese-side-frame"].geometry}
        material={materials["eye-ball-black"]}
      />
      <mesh
        geometry={nodes["right-eye"].geometry}
        material={materials["eye-ball-material"]}
      />
      <mesh
        geometry={nodes["left-eye"].geometry}
        material={materials["eye-ball-material"]}
      />
      <mesh
        geometry={nodes["male-head-neck"].geometry}
        material={materials.SVGMat}
      />
    </group>
  );
}

useGLTF.preload("./models/male-head/male-head.glb");
