/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/door/door.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function PortalGate(props) {
  const { nodes, materials } = useGLTF("/models/door/door.glb ");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube324.geometry} material={materials.Wood} />
      <mesh
        position={[0, 0, 0]}
        geometry={nodes.Cube324_1.geometry}
        material={materials["metal-brass"]}
      />
    </group>
  );
}

useGLTF.preload("/models/door/door.glb ");

