/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/design-works/masu-typo/masu-typo.glb 
*/

import React, { useRef } from "react";
import { useGLTF, Text } from "@react-three/drei";

export default function MasuTypo(props) {
  const { nodes, materials } = useGLTF(
    "./models/design-works/masu-typo/masu-typo.glb "
  );
  return (
    <group {...props} dispose={null}>
      {/* TOPIC */}
      <group scale={5} position={[-28, 10, 5]}>
        <Text
          color="white"
          anchorX="center"
          anchorY="middle"
          font="./fonts/shippori-mincho-b1-v21-japanese-800.woff"
          characters="abcdefghijklmnopqrstuvwxyz0123456789!"
        >
          Masu Typo
        </Text>
      </group>
      <mesh
        geometry={nodes["typo-alphabet-a002"].geometry}
        material={materials["white-matt-typography"]}
      />
      <mesh
        geometry={nodes["typo-alphabet-b002"].geometry}
        material={materials["white-matt-typography"]}
      />
      <mesh
        geometry={nodes["typo-alphabet-c002"].geometry}
        material={materials["white-matt-typography"]}
      />
      <mesh
        geometry={nodes["typo-hiragana-a002"].geometry}
        material={materials["white-matt-typography"]}
      />
      <mesh
        geometry={nodes["typo-hiragana-i002"].geometry}
        material={materials["white-matt-typography"]}
      />
      <mesh
        geometry={nodes["typo-hiragana-u002"].geometry}
        material={materials["white-matt-typography"]}
      />
      <mesh
        geometry={nodes["back-lighting"].geometry}
        material={materials["emission-typography"]}
      />
      <mesh
        geometry={nodes.grid.geometry}
        material={materials["white-matt-typography"]}
      />
    </group>
  );
}

useGLTF.preload("./models/design-works/masu-typo/masu-typo.glb ");
